/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-11-08 09:45:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/icp/include/import.jsp", Long.valueOf(1475203760434L));
    _jspx_dependants.put("/icp/include/taglib.jsp", Long.valueOf(1478489851195L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      java.util.Date now = null;
      now = (java.util.Date) _jspx_page_context.getAttribute("now", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (now == null){
        now = new java.util.Date();
        _jspx_page_context.setAttribute("now", now, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>浪潮云服务</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<meta http-equiv=\"refresh\" content=\"3600\"/>\r\n");
      out.write("\t\t");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/homepage.css\" type=\"text/css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/index.css\" type=\"text/css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/style2.css\" type=\"text/css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/miniui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/easyui-1.4/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/easyui-1.4/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/easyui-1.4/jquery.easyui.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/easyui-1.4/locale/easyui-lang-zh_CN.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/util.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/gather.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/slide.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/jquery.blockUI.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/highchart/highcharts.js\"  ></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/homepage/jquery-ui.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
 String contextPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function (){\r\n");
      out.write("            $(\"#tabs\").tabs({\r\n");
      out.write("                //event: \"mouseover\"\r\n");
      out.write("            });\r\n");
      out.write("            alerm();\r\n");
      out.write("         \tresource();\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function alerm(){\r\n");
      out.write("\t\t\t $('#alarmdg').datagrid({\r\n");
      out.write("\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/homepage/queryAlarm.do',\r\n");
      out.write("\t\t\t\tpagination:false,//分页控件\r\n");
      out.write("\t\t\t\t showFooter:false,\r\n");
      out.write("\t\t\t\t width:'100%',\r\n");
      out.write("\t\t\t\t height:300,\r\n");
      out.write("\t\t\t\tpageSize:5,\r\n");
      out.write("\t\t\t\tpageList:[5],\r\n");
      out.write("\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\thalign:'center',\r\n");
      out.write("\t\t\t\tfitColumns:true,\r\n");
      out.write("\t\t\t\tsingleSelect:true,\r\n");
      out.write("\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\tscrollbarSize:0,\r\n");
      out.write("\t\t\t\tcolumns:[[{\r\n");
      out.write("\t\t\t\t\ttitle:'类型',\r\n");
      out.write("\t\t\t\t\tfield:'eventype',\r\n");
      out.write("\t\t\t\t\twidth:'15%',\r\n");
      out.write("\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\t styler: function(value,row,index){\r\n");
      out.write("                               return 'vertical-align:middle;';\r\n");
      out.write("                       },\r\n");
      out.write("                       formatter:function(value,row,index){\r\n");
      out.write("                       \tswitch (value) {\r\n");
      out.write("                           \tcase 'alarm':\r\n");
      out.write("                           \t\treturn \"<font color=\\\"#000\\\">故障</font>\";\r\n");
      out.write("                           \tcase 'event':\r\n");
      out.write("                           \t\treturn \"<font color=\\\"#000\\\">事件</font>\";\r\n");
      out.write("                           \tcase 'degradation':\r\n");
      out.write("                           \t\treturn \"<font color=\\\"#000\\\">劣化</font>\";\r\n");
      out.write("                           \tcase 'notice':\r\n");
      out.write("                           \t\treturn \"<font color=\\\"#000\\\">通知</font>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttitle:'重要',\r\n");
      out.write("\t\t\t\t\tfield:'serious',\r\n");
      out.write("\t\t\t\t\twidth:'17%',\r\n");
      out.write("\t\t\t\t\tfit:true,\r\n");
      out.write("\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\tstyler: function(value,row,index){\r\n");
      out.write("                               return 'vertical-align:middle;';\r\n");
      out.write("                       },\r\n");
      out.write("                       formatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<font color=\\\"#fc0e02\\\">\"+value+\"</font>\";\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttitle:'主要',\r\n");
      out.write("\t\t\t\t\tfield:'major',\r\n");
      out.write("\t\t\t\t\twidth:'17%',\r\n");
      out.write("\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\tstyler: function(value,row,index){\r\n");
      out.write("                               return 'vertical-align:middle;';\r\n");
      out.write("                       },\r\n");
      out.write("                       formatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<font color=\\\"#021afc\\\">\"+value+\"</font>\";\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttitle:'次要',\r\n");
      out.write("\t\t\t\t\tfield:'secondary',\r\n");
      out.write("\t\t\t\t\twidth:'17%',\r\n");
      out.write("\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\tstyler: function(value,row,index){\r\n");
      out.write("                               return 'vertical-align:middle;';\r\n");
      out.write("                       },\r\n");
      out.write("                       formatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<font color=\\\"#02fc14\\\">\"+value+\"</font>\";\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\ttitle:'一般',\r\n");
      out.write("\t\t\t\t\tfield:'commonly',\r\n");
      out.write("\t\t\t\t\twidth:'17%',\r\n");
      out.write("\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\tstyler: function(value,row,index){\r\n");
      out.write("                               return 'vertical-align:middle;';\r\n");
      out.write("                       },\r\n");
      out.write("                       formatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<font color=\\\"#fc8902\\\">\"+value+\"</font>\";\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("                       },{\r\n");
      out.write("\t\t\t\t\ttitle:'警告',\r\n");
      out.write("\t\t\t\t\tfield:'warning',\r\n");
      out.write("\t\t\t\t\twidth:'17%',\r\n");
      out.write("\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\tstyler: function(value,row,index){\r\n");
      out.write("                               return 'vertical-align:middle;';\r\n");
      out.write("                       },\r\n");
      out.write("                       formatter:function(value,row,index){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<font color=\\\"#fcf302\\\">\"+value+\"</font>\";\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t}]]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("   }\r\n");
      out.write("        \r\n");
      out.write("        function resource(){\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("   \t\t\t\t  \t\ttype : 'post',\r\n");
      out.write("   \t\t\t\t  \t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/homepage/queryResource.do',\r\n");
      out.write("   \t\t\t\t  \t\tsuccess:function(rets){\r\n");
      out.write("   \t\t\t\t  \t\tvar ret = JSON.parse(rets);\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageTenants').html(ret.custnum);\r\n");
      out.write("   \t\t\t\t  \t\t\t\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageRedRquipment').html(ret.errnenum );\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageGreenRquipment').html(ret.normalnenum );\r\n");
      out.write("   \t\t\t\t  \t\t\t\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageRedApply').html(ret.errappnum);\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageGreenApply').html(ret.normalappnum );\r\n");
      out.write("   \t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t  \t\t\t/* $('#homepageRedSystem').html(ret.homepageRedSystem);\r\n");
      out.write("\t\t\t\t  \t\t\t$('#homepageGreenSystem').html(ret.homepageGreenSystem ); */\r\n");
      out.write("\t\t\t\t  \t\t\t\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageAttack').html(ret.attacknum);\r\n");
      out.write("   \t\t\t\t  \t\t\t\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageRedIP').html(ret.ipused );\r\n");
      out.write("\t\t\t\t  \t\t\t$('#homepageGreenIP').html(ret.ipunused);\r\n");
      out.write("\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t  \t\t\t$('#homepageInhost').html(ret.hostnum );\r\n");
      out.write("   \t\t\t\t  \t\t\t$('#homepageInserver').html(ret.vmnum);\r\n");
      out.write("   \t\t\t\t  \t\t\tqueryHighcharts(ret);\r\n");
      out.write("   \t\t\t\t  \t\t\thomepagecpulan(ret);\r\n");
      out.write("   \t\t\t\t  \t\t\t\r\n");
      out.write("   \t\t\t\t  \t\t}\r\n");
      out.write("\t\t   \t});\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function queryHighcharts(rets){\r\n");
      out.write("        \tvar obj = JSON.parse(rets.cpuloadtop10);\r\n");
      out.write("\t  \t\thighchartsOne (obj.categories,obj.data);\r\n");
      out.write("\t  \t\tvar mobj = JSON.parse(rets.memloadtop10);\r\n");
      out.write("\t  \t\thighchartsTwo (mobj.categories,mobj.data);\r\n");
      out.write("        \t\r\n");
      out.write("        }\r\n");
      out.write("          function queryHighchartsOne(){\r\n");
      out.write("\t        \t$.ajax({\r\n");
      out.write("\t   \t\t\t\t  \t\ttype : 'post',\r\n");
      out.write("\t   \t\t\t\t  \t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/homepage/queryResource.do',\r\n");
      out.write("\t   \t\t\t\t  \t\tsuccess:function(rets){\r\n");
      out.write("\t\t   \t\t\t\t  \t\tvar obj = JSON.parse(rets.cpuloadtop10);\r\n");
      out.write("\t\t   \t\t\t\t  \t\thighchartsOne (obj.categories,obj.data);\r\n");
      out.write("\t   \t\t\t\t  \t\t}\r\n");
      out.write("\t   \t\t\t});\r\n");
      out.write("   \t\t\t}\r\n");
      out.write("   \t\t\tfunction queryHighchartsTwo(){\r\n");
      out.write("\t        \t$.ajax({\r\n");
      out.write("\t   \t\t\t\t  \t\ttype : 'post',\r\n");
      out.write("\t   \t\t\t\t  \t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/homepage/queryResource.do',\r\n");
      out.write("\t   \t\t\t\t  \t\tsuccess:function(rets){\r\n");
      out.write("\t\t   \t\t\t\t  \t\tvar mobj = JSON.parse(rets.memloadtop10);\r\n");
      out.write("\t\t   \t\t\t\t  \t\thighchartsTwo (mobj.categories,mobj.data);\r\n");
      out.write("\t   \t\t\t\t  \t\t}\r\n");
      out.write("\t   \t\t\t});\t  \t\t\r\n");
      out.write("   \t\t\t}\r\n");
      out.write("   \t\t\t\t  \t\t\r\n");
      out.write("         function highchartsOne(categoriess,datas){\r\n");
      out.write("\t\t\tcategories =categoriess,\r\n");
      out.write("\t\t\t//categories = ['主机1', '主机2', '主机3', '主机4', '主机5','主机6', '主机7', '主机8', '主机9', '主机10'],\r\n");
      out.write("\t\t\tname = ' ',\r\n");
      out.write("\t\t\tdata = datas;\r\n");
      out.write("\r\n");
      out.write("\t\t    function setChart(name, categories, data) {\r\n");
      out.write("\t\t\tchart.xAxis[0].setCategories(categories, false);\r\n");
      out.write("\t\t\tchart.series[0].remove(false);\r\n");
      out.write("\t\t\tchart.addSeries({\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t}, false);\r\n");
      out.write("\t\t\tchart.redraw();\r\n");
      out.write("\t\t    }\r\n");
      out.write("\r\n");
      out.write("\t\t    var chart = $('#container').highcharts({\r\n");
      out.write("\t\t         chart: {\r\n");
      out.write("\t\t            type: 'column'\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        title: {\r\n");
      out.write("\t\t            text:null\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        subtitle: {\r\n");
      out.write("\t\t            text: null\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        tooltip:{\r\n");
      out.write("\t\t      \t   formatter:function(){\r\n");
      out.write("\t\t      \t      return'名称：'+this.x+'<br/>数值： '+Highcharts.numberFormat(this.y,2,'.')+\"%\";\r\n");
      out.write("\t\t      \t   }\r\n");
      out.write("\t\t      \t},\r\n");
      out.write("\t\t        xAxis: {\r\n");
      out.write("\t\t            categories: categories\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        yAxis: {\r\n");
      out.write("\t\t            title: {\r\n");
      out.write("\t\t                text:null\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        plotOptions: {\r\n");
      out.write("\t\t            column: {\r\n");
      out.write("\t\t                cursor: 'pointer',\r\n");
      out.write("\t\t                dataLabels: {\r\n");
      out.write("\t\t                    enabled: false,\r\n");
      out.write("\t\t                    formatter: function() {\r\n");
      out.write("\t\t                        return this.y +'%';\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t        series: [{\r\n");
      out.write("\t\t            name: name,\r\n");
      out.write("\t\t            data: data,\r\n");
      out.write("\t\t        }],\r\n");
      out.write("\t\t    })\r\n");
      out.write("    .highcharts();\r\n");
      out.write("};\t\r\n");
      out.write("\tfunction highchartsTwo(categoriess,datas){\r\n");
      out.write("\t\t\tcategories = categoriess;\r\n");
      out.write("\t\t\tname = ' ',\r\n");
      out.write("\t\t\tdata = datas;\r\n");
      out.write("\t\t    function setChart(name, categories, data, color) {\r\n");
      out.write("\t\t\tchart.xAxis[0].setCategories(categories, false);\r\n");
      out.write("\t\t\tchart.series[0].remove(false);\r\n");
      out.write("\t\t\tchart.addSeries({\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\tcolor: color\r\n");
      out.write("\t\t\t}, false);\r\n");
      out.write("\t\t\tchart.redraw();\r\n");
      out.write("\t\t    }\r\n");
      out.write("\r\n");
      out.write("\t\t    var chart = $('#container2').highcharts({\r\n");
      out.write("\t\t        chart: {\r\n");
      out.write("\t\t            type: 'column'\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        title: {\r\n");
      out.write("\t\t            text:null\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        subtitle: {\r\n");
      out.write("\t\t            text: null\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        tooltip:{\r\n");
      out.write("\t\t      \t   formatter:function(){\r\n");
      out.write("\t\t      \t      return'名称：'+this.x+'<br/>数值： '+Highcharts.numberFormat(this.y,2,'.')+\"%\";\r\n");
      out.write("\t\t      \t   }\r\n");
      out.write("\t\t      \t},\r\n");
      out.write("\t\t        xAxis: {\r\n");
      out.write("\t\t            categories: categories\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        yAxis: {\r\n");
      out.write("\t\t            title: {\r\n");
      out.write("\t\t                text: ''\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        plotOptions: {\r\n");
      out.write("\t\t            column: {\r\n");
      out.write("\t\t                cursor: 'pointer',\r\n");
      out.write("\t\t                dataLabels: {\r\n");
      out.write("\t\t                    enabled: false,\r\n");
      out.write("\t\t                    formatter: function() {\r\n");
      out.write("\t\t                        return this.y +'%';\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t        series: [{\r\n");
      out.write("\t\t            name: name,\r\n");
      out.write("\t\t            data: data,\r\n");
      out.write("\t\t        }],\r\n");
      out.write("\t\t    })\r\n");
      out.write("\t\t    .highcharts();\r\n");
      out.write("\t\t};\t\t\t\t\t\t\t\r\n");
      out.write("        \r\n");
      out.write("        function homepagecpulan(ret) {\r\n");
      out.write("        \tvar num1 = ret.throughput;\r\n");
      out.write("        \tvar num2 = ret.bandwidthusage;\r\n");
      out.write("        \tvar num3 = ret.vmcpuusage;\r\n");
      out.write("        \tvar num4 = ret.storagecentused;\r\n");
      out.write("        \tvar num5 = ret.storagedistused;\r\n");
      out.write("        \tvar num6 = ret.vmmemusage;\r\n");
      out.write("        \tvar num7 = ret.hostcpuusage;\r\n");
      out.write("        \tvar num8 = ret.hostmemusage;\r\n");
      out.write("        \t//alert(num1+\"--\"+num2+\"--\"+num3+\"--\"+num4+\"--\"+num5+\"--\"+num6+\"--\"+num7+\"--\"+num8);\r\n");
      out.write("            $('#homepagethroughput').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false,\r\n");
      out.write("                    width:106,\r\n");
      out.write("                    height:98,\r\n");
      out.write("                },\r\n");
      out.write("                //colors:['deepskyblue','silver'],\r\n");
      out.write("                 colors:['#66c96f','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num1+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '11px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '吞吐利用率',\r\n");
      out.write("                            y: num1,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['其它',100-num1],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            \r\n");
      out.write("            $('#homepagebandwidth').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false,\r\n");
      out.write("                    width:106,\r\n");
      out.write("                    height:98,\r\n");
      out.write("                },\r\n");
      out.write("                colors:['#ff9c2a','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num2+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '11px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '带宽利用率',\r\n");
      out.write("                            y: num2,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['带宽剩余',100-num2],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            $('#homepageinservercpu').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false\r\n");
      out.write("                },\r\n");
      out.write("                colors:['#59a70e','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num3+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '16px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '虚拟机CPU利用率',\r\n");
      out.write("                            y: num3,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['虚拟机CPU剩余',100-num3],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            $('#homepageCentralized').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false\r\n");
      out.write("                },\r\n");
      out.write("                colors:['#ff7070','silver'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num4+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '16px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '集中存储利用率',\r\n");
      out.write("                            y: num4,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['集中存储剩余',100-num4],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            $('#homepageDistributed').highcharts({\r\n");
      out.write("            \t chart: {\r\n");
      out.write("                     plotBackgroundColor: null,\r\n");
      out.write("                     plotBorderWidth: 0,\r\n");
      out.write("                     plotShadow: false\r\n");
      out.write("                 },\r\n");
      out.write("                colors:['#23b1f3','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num5+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '16px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '分布式存储利用率',\r\n");
      out.write("                            y: num5,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['分布式存储剩余',100-num5],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            $('#homepageinservermemory').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false\r\n");
      out.write("                },\r\n");
      out.write("                colors:['#fb320b','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num6+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '16px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '虚拟机内存利用率',\r\n");
      out.write("                            y: num6,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['虚拟机内存剩余',100-num6],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            $('#homepageinhostcpu').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false\r\n");
      out.write("                },\r\n");
      out.write("                colors:['#4EEE94','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num7+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '16px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '物理机内存利用率',\r\n");
      out.write("                            y: num7,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['物理机内存剩余',100-num7],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            }),\r\n");
      out.write("            $('#homepageinhostmemory').highcharts({\r\n");
      out.write("                chart: {\r\n");
      out.write("                    plotBackgroundColor: null,\r\n");
      out.write("                    plotBorderWidth: 0,\r\n");
      out.write("                    plotShadow: false\r\n");
      out.write("                },\r\n");
      out.write("                colors:['#EE5C42','#ccc'],\r\n");
      out.write("                title: {\r\n");
      out.write("                    text: num8+'%',\r\n");
      out.write("                    align: 'center',\r\n");
      out.write("                    verticalAlign: 'middle',\r\n");
      out.write("                    style:{\r\n");
      out.write("                    \tfontSize: '16px',\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                credits:{\r\n");
      out.write("                    enabled: false,\r\n");
      out.write("                },\r\n");
      out.write("                tooltip: {\r\n");
      out.write("                    pointFormat: '数值: <b>{point.percentage:.1f}%</b>'\r\n");
      out.write("                },\r\n");
      out.write("                plotOptions: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        dataLabels: {\r\n");
      out.write("                            enabled: false,\r\n");
      out.write("                            distance: -50,\r\n");
      out.write("                            style: {\r\n");
      out.write("                                fontWeight: 'bold',\r\n");
      out.write("                                color: 'white',\r\n");
      out.write("                                textShadow: '0px 1px 2px 0px'\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        startAngle: -180,\r\n");
      out.write("                        endAngle: 180,\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                series: [{\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    name: '',\r\n");
      out.write("                    innerSize: '50%',\r\n");
      out.write("                    data: [\r\n");
      out.write("                        {\r\n");
      out.write("                            name: '物理机内存利用率',\r\n");
      out.write("                            y: num8,\r\n");
      out.write("                            dataLabels: {\r\n");
      out.write("                                enabled: false\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        ['物理机内存剩余',100-num8],\r\n");
      out.write("                    ]\r\n");
      out.write("                }]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        function passwdChange(){\r\n");
      out.write("        \twindow.parent.window.querymenu('%/systemMg/userMgr.jsp%');\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function enterAlarm(){\r\n");
      out.write("        \twindow.parent.window.querymenu('%/alarmMg/eventActive.jsp%');\r\n");
      out.write("        }\r\n");
      out.write("        function refreshOne(){\r\n");
      out.write("        \t//queryHighchartsOne();\r\n");
      out.write("        \tqueryHighcharts();\r\n");
      out.write("        } \r\n");
      out.write("        \r\n");
      out.write("        function refreshTwo(){\r\n");
      out.write("        \t//queryHighchartsTwo();\r\n");
      out.write("        \tqueryHighcharts();\r\n");
      out.write("        } \r\n");
      out.write("        function Over(o){o.style.backgroundColor='#fff'; o.style.border='1px solid #58c9f3';}\r\n");
      out.write("        function Out(o){o.style.backgroundColor='#fff'; o.style.border='1px dotted #CCC';}\r\n");
      out.write("\r\n");
      out.write("      //修改密码\r\n");
      out.write("      function passwordChange() {\r\n");
      out.write("        \t$('<div></div>').dialog({\r\n");
      out.write("        \t\tid: 'passwdID',\r\n");
      out.write("        \t\ttitle: '密码修改',\r\n");
      out.write("        \t\twidth: 500,\r\n");
      out.write("        \t\theight: 260,\r\n");
      out.write("        \t\tclosed: false,\r\n");
      out.write("        \t\tcache: false,\r\n");
      out.write("        \t\thref: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/systemMg/passwordChange.jsp',\r\n");
      out.write("        \t\tmodal: true,\r\n");
      out.write("        \t\tbuttons: [{\r\n");
      out.write("        \t\t\ttext: '确定',\r\n");
      out.write("        \t\t\ticonCls: 'icon-ok',\r\n");
      out.write("        \t\t\thandler: function () {\r\n");
      out.write("        \t\t\t\t\t\t\t\r\n");
      out.write("        \t\t\t\t$('#passwdChange_email').val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("        \t\t\t\t$('#passwdChange_Form').form('submit',{\r\n");
      out.write("        \t\t\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/authMgr/changePasswd.do',\r\n");
      out.write("        \t\t\t\t\t\t\tonSubmit:function(){\r\n");
      out.write("        \t\t\t\t\t\t           var flag = passwdChangeCheck();\r\n");
      out.write("        \t\t\t\t\t\t           if(!flag){\r\n");
      out.write("        \t\t\t\t\t\t            return flag;  \r\n");
      out.write("        \t\t\t\t\t\t           }\r\n");
      out.write("        \t\t\t\t\t\t           return true;\r\n");
      out.write("        \t\t\t\t\t\t         },\r\n");
      out.write("        \t\t\t\t\t\t\tsuccess:function(r){\r\n");
      out.write("        \t\t\t\t\t\t\t\tvar obj = jQuery.parseJSON(r);\r\n");
      out.write("        \t\t\t\t\t\t\t\tif(obj.success){\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t$('#passwdID').dialog('close');\t\t\t\t\t\t\t\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\", obj.msg+\",请重新登录!\", \"info\", function () {  \r\n");
      out.write("        \t\t\t\t\t\t\t\t\t\t//logout(); \r\n");
      out.write("        \t\t\t\t\t\t\t\t\t\t//window.parent.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/userMgr/logout.do\";\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t    window.parent.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login.jsp\";\r\n");
      out.write("        \t\t\t\t\t\t\t        });  \r\n");
      out.write("        \t\t\t\t\t\t\t\t}else{\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t\ttitle:'提示',\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t\tmsg:obj.msg\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t});\r\n");
      out.write("        \t\t\t\t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\t\t});\t\t\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t}, {\r\n");
      out.write("        \t\t\ttext: '取消',\r\n");
      out.write("        \t\t\ticonCls: 'icon-cancel',\r\n");
      out.write("        \t\t\thandler: function () {\r\n");
      out.write("        \t\t\t\t$(\"#passwdID\").dialog('destroy');\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t}]\r\n");
      out.write("        \t});\r\n");
      out.write("       }\r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"homepagecontainer\">\r\n");
      out.write("\t\t<!-- 上部 -->\r\n");
      out.write("\t\t\t<div class=\"homepagecontainer_k\"></div>\r\n");
      out.write("\t\t\t<div class=\"homepagecontainer_top\" >\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_top_space\" style=\"float: left;\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("\t\t\t\t\t<div class=\"homepagecontainer_top_space_title\">\r\n");
      out.write("\t\t\t\t\t\t<div class=homepagecontainer_top_space_title_fant>账户信息</div>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/images/admin2.png\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homeleft_top_center_name\">\r\n");
      out.write("\t\t\t\t\t\t\t<span title=\"用户名\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span> ·\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t \t<span onclick=\"passwordChange()\">修改密码</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homeleft_third\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homeleft_third_one\" style=\"border-right: 1px solid #ddd;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span title=\"邮箱\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span title=\"手机\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homeleft_third_one\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"gdname\"  title=\"上次登陆时间\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"unitname\" title=\"系统名称\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homeleft_button\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" onclick=\"passwdChange()\" >管理账户</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_top_space\" style=\"float: left;margin-left: 1.3%\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("<!-- \t\t\t\t\t <div id=\"tabs\"> -->\r\n");
      out.write("<!-- \t\t\t\t        <ul> -->\r\n");
      out.write("<!-- \t\t\t\t            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/include/tab1.jsp\">待办工单</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/include/tab2.jsp\">已办工单</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/include/tab3.jsp\">办结工单</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t        </ul> -->\r\n");
      out.write("<!--   \t\t\t\t\t  </div> -->\r\n");
      out.write("                <iframe id=\"omshomepage_frame\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/include/tab0.jsp\" style=\"width:100%;height:100%;border:0px\"></iframe>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_top_space\" style=\"float: right;\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("\t\t\t\t\t<div class=\"homerighrt-up-space\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homerighrt-up-space-fonts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homerighrt-up-space-fonts-span\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>告警信息</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homerighrt-up-space-fonts-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/images/enter.png\"  onclick=\"enterAlarm()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homerighrt-down-space\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"homealem-layout\" class=\"easyui-layout\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table id=\"alarmdg\" style=\"background:#eee;text-align:center;\"></table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- 中部 -->\r\n");
      out.write("\t\t\t<div class=\"homepagecontainer_center\">\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_k\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_center_top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"homepagecontainer_center_top_space\" style=\"width:24.5%;float: left;\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_xg\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right_backgroud_xg\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left\" style=\"cursor: pointer\"title=\"租户数量\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_top\" style=\"cursor: pointer\"title=\"租户数量\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span  id = \"homepageTenants\" title=\"租户数量\" >0</span>个\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>租户数量</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left\" style=\"cursor: pointer\"title=\"应用数量\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_top\" style=\"cursor: pointer\"title=\"应用数量\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span  id = \"homepageRedApply\" title=\"应用数量\" >0</span>个\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>应用数量</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"homepagecontainer_center_top_space\" style=\"width:74.5%;float: right;padding: 0;\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_backgroud\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left\" style=\"cursor: pointer\"title=\"物理机数量\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_top\" style=\"cursor: pointer\"title=\"物理机\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span  id = \"homepageInhost\" title=\"物理机\" >0</span>台\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>物理机</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left\"  style=\"cursor: pointer\"title=\"虚拟机数量\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_top\" style=\"cursor: pointer\"title=\"虚拟机\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id = \"homepageInserver\"  title=\"虚拟机\" >0</span>台\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_left_left_bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>虚拟机</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\tclass=\"homepagecontainer_center_top_space_right_left\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"homepageinhostcpu\" class=\"homepagecontainer_center_top_space_right_left_top\" ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right_left_botm\"><span>物理机CPU利用率</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div\tclass=\"homepagecontainer_center_top_space_right_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"homepageinhostmemory\" class=\"homepagecontainer_center_top_space_right_left_top\" ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right_left_botm\"><span>物理机内存利用率</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right\">\r\n");
      out.write("\t\t\t\t\t\t\t<div\tclass=\"homepagecontainer_center_top_space_right_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"homepageinservercpu\"  class=\"homepagecontainer_center_top_space_right_left_top\" ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right_left_botm\"><span>虚拟机CPU利用率</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"homepageinservermemory\" class=\"homepagecontainer_center_top_space_right_left_top\" ></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"homepagecontainer_center_top_space_right_left_botm\"><span>虚拟机内存利用率</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- 下部 -->\r\n");
      out.write("\t\t\t<div class=\"homepagecontainer_k\"></div>\r\n");
      out.write("\t\t\t<div class=\"homepagecontainer_bottom\">\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_bottom_space\" style=\"float: left;\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("\t\t\t\t\t<div class=\"homecontainer-bot-left-space\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homecontainer-bot-left-space-fonts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>CPU负荷TOP10</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/images/refresh.png\"  onclick=\"refreshOne()\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"homecontainer-bot-items-space\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"container\" style=\"min-width:100%;height:100%\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"homepagecontainer_bottom_space\" style=\"float: right;\" onmouseover=Over(this); onmouseout=Out(this);>\r\n");
      out.write("\t\t\t\t\t<div class=\"homecontainer-bot-right-space\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"homecontainer-bot-right-space-fonts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>内存利用率TOP10</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/images/refresh.png\"  onclick=\"refreshTwo()\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"homecontainer-bot-items-space\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"container2\" style=\"min-width:100%;height:100%\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /icp/include/taglib.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /icp/include/taglib.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /web/homePage.jsp(830,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.email == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("没有数据");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /web/homePage.jsp(831,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.email!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /web/homePage.jsp(835,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.mobile == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("没有数据");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /web/homePage.jsp(836,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.mobile!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /web/homePage.jsp(845,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.lastlogin == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("没有数据");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent(null);
    // /web/homePage.jsp(846,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.lastlogin!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.lastlogin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f6.setParent(null);
    // /web/homePage.jsp(851,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.sysname == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
    if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("没有数据");
        int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f7.setParent(null);
    // /web/homePage.jsp(852,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.sysname!=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
    if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.sysname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
    return false;
  }
}
