/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-11-09 02:54:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/web/../icp/include/taglib.jsp", Long.valueOf(1478489851195L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();

      out.write('\r');
      out.write('\n');
      java.util.Date now = null;
      now = (java.util.Date) _jspx_page_context.getAttribute("now", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (now == null){
        now = new java.util.Date();
        _jspx_page_context.setAttribute("now", now, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>浪潮云服务</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<!--<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/miniui.css\" />-->\t\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/easyui-1.4/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/easyui-1.4/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/easyui-1.4/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/js/easyui-1.4/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/icpindex.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\t\t\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tresourceOverview();\r\n");
      out.write("    indexGetHeight();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function indexGetHeight() {\r\n");
      out.write("    var screenH = $(window).height() - 60;\r\n");
      out.write("    var leftH = $('.index-left').height();\r\n");
      out.write("    var rightH = $('.index-right').height();\r\n");
      out.write("    var maxH = screenH - (leftH - rightH > 0 ? leftH : rightH) > 0 ? screenH : leftH - rightH > 0 ? leftH : rightH;\r\n");
      out.write("    $('.index-left').height(maxH);\r\n");
      out.write("    $('.index-right').height(maxH);\r\n");
      out.write("}\r\n");
      out.write("//统计资源\r\n");
      out.write("function resourceOverview() {\r\n");
      out.write("\t$.ajax( {\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\turl : '");
      out.print(contextPath);
      out.write("/getResourceOverview.do',\r\n");
      out.write("\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\tvar obj = JSON.parse(result);\r\n");
      out.write("\t\t\t//业务\r\n");
      out.write("\t\t\t//待办工单\r\n");
      out.write("\t\t\t$(\"#todoorder\").html(obj.todoorder);\r\n");
      out.write("\t\t\t$(\"#messagetodo\").html(obj.todoorder);\r\n");
      out.write("\t\t\t//已办工单\r\n");
      out.write("\t\t\t$(\"#doorder\").html(obj.doorder);\r\n");
      out.write("\t\t\t//资源申请\r\n");
      out.write("\t\t\t$(\"#applyresource\").html(obj.applyresource);\r\n");
      out.write("\t\t\t//资源变更\r\n");
      out.write("\t\t\t$(\"#modifyresource\").html(obj.modifyresource);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t//资源\r\n");
      out.write("\t\t\t$(\"#vmnum\").html(obj.vmnum);\r\n");
      out.write("\t\t\t$(\"#resourcepilotrunnum\").html(obj.resourcepilotrunnum);\r\n");
      out.write("\t\t\t$(\"#resourcestartfeenum\").html(obj.resourcestartfeenum);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//部门费用\t\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#monthfee\").html(obj.monthfee);\t\t\r\n");
      out.write("\t\t\t$(\"#yearfee\").html(obj.yearfee);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//监控\r\n");
      out.write("\t\t\t$(\"#alarm\").html(obj.alarm);\r\n");
      out.write("\t\t\t$(\"#breakdown\").html(obj.breakdown);\r\n");
      out.write("\t\t\t$(\"#event\").html(obj.event);\r\n");
      out.write("\t\t\t$(\"#degradation\").html(obj.degradation);\r\n");
      out.write("\t\t\t$(\"#notice\").html(obj.notice);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//项目\r\n");
      out.write("\t\t\t$(\"#projectnum\").html(obj.projectnum);\r\n");
      out.write("\t\t\t//应用\r\n");
      out.write("\t\t\t$(\"#appnum\").html(obj.appnum);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t//通知公告\t\t\t\r\n");
      out.write("\t\t\t$(\"#messagenum\").html(obj.messagenum);\r\n");
      out.write("\t\t\t$(\"#infonum\").html(obj.infonum);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//修改密码\r\n");
      out.write("function passwordChange() {\r\n");
      out.write("\r\n");
      out.write("\t$('<div></div>').dialog({\r\n");
      out.write("\t\tid: 'passwdID',\r\n");
      out.write("\t\ttitle: '密码修改',\r\n");
      out.write("\t\twidth: 500,\r\n");
      out.write("\t\theight: 260,\r\n");
      out.write("\t\tclosed: false,\r\n");
      out.write("\t\tcache: false,\r\n");
      out.write("\t\thref: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/systemMg/passwordChange.jsp',\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tbuttons: [{\r\n");
      out.write("\t\t\ttext: '确定',\r\n");
      out.write("\t\t\ticonCls: 'icon-ok',\r\n");
      out.write("\t\t\thandler: function () {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#passwdChange_email').val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t\t$('#passwdChange_Form').form('submit',{\r\n");
      out.write("\t\t\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/authMgr/changePasswd.do',\r\n");
      out.write("\t\t\t\t\t\t\tonSubmit:function(){\r\n");
      out.write("\t\t\t\t\t\t           var flag = passwdChangeCheck();\r\n");
      out.write("\t\t\t\t\t\t           if(!flag){\r\n");
      out.write("\t\t\t\t\t\t            return flag;  \r\n");
      out.write("\t\t\t\t\t\t           }\r\n");
      out.write("\t\t\t\t\t\t           return true;\r\n");
      out.write("\t\t\t\t\t\t         },\r\n");
      out.write("\t\t\t\t\t\t\tsuccess:function(r){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar obj = jQuery.parseJSON(r);\r\n");
      out.write("\t\t\t\t\t\t\t\tif(obj.success){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#passwdID').dialog('close');\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\", obj.msg+\",请重新登录!\", \"info\", function () {  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//logout();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//window.parent.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/userMgr/logout.do\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    window.parent.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login.jsp\";\r\n");
      out.write("\t\t\t\t\t\t\t        });  \r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle:'提示',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmsg:obj.msg\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\ttext: '取消',\r\n");
      out.write("\t\t\ticonCls: 'icon-cancel',\r\n");
      out.write("\t\t\thandler: function () {\r\n");
      out.write("\t\t\t\t$(\"#passwdID\").dialog('destroy');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}]\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\t\t\r\n");
      out.write("\t<body style=\"position: static;\">\t\r\n");
      out.write("\t\t\t<div class=\"index-left\">\r\n");
      out.write("\t\t\t\t<!-- 头像 -->\r\n");
      out.write("\t\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t\t<img class=\"info-photo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/icp/style/images/icpindex/photo.jpg\" width=\"65\" height=\"65\">\r\n");
      out.write("\t\t\t\t\t<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.sysname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t<button class=\"info-btn\">账户设置</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 修改密码和电话 -->\r\n");
      out.write("\t\t\t\t<div class=\"det\">\r\n");
      out.write("\t\t\t\t\t<div class=\"det-text\">\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"det-password\" onclick=\"passwordChange()\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text\">距离密码过期还有<em>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionUser.timelength}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</em>天</p> <span class=\"btn-password\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 提醒 -->\r\n");
      out.write("\t\t\t\t<ul class=\"dealt\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-dealt icon-dealt-tzgg\"></i>站内消息<span class=\"quan\" id=\"infonum\">0</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-dealt icon-dealt-dbxx\"></i>待办工单<span class=\"quan\" id=\"messagetodo\">0</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"icon-dealt icon-dealt-gjxx\"></i>告警信息<span class=\"quan\" id=\"alarm\">0</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"index-right\">\r\n");
      out.write("        <div class=\"con\">\r\n");
      out.write("            <div class=\"rowbox\">\r\n");
      out.write("                <div class=\" span span33\">\r\n");
      out.write("                    <!-- 业务 -->\r\n");
      out.write("                    <div class=\"item-wrap business-wrap\">\r\n");
      out.write("                        <em class=\"item-icon\"></em>\r\n");
      out.write("                        <dl>\r\n");
      out.write("                            <dt>资源审批\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>待办工单：<em class=\"text-big\" id=\"todoorder\"><span id=\"todoorder\">0</span></em></dd>\r\n");
      out.write("                            <dd>已办工单：<em class=\"text-big\" id=\"doorder\"><span id=\"doorder\">0</span></em></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl>\r\n");
      out.write("                            <dt>资源申请\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>资源申请：<em class=\"text-big\" id=\"applyresource\"><span id=\"applyresource\">0</span></em></dd>\r\n");
      out.write("                            <dd>资源变更：<em class=\"text-big\" id=\"modifyresource\"><span id=\"modifyresource\">0</span></em></dd>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\" span span66\">\r\n");
      out.write("                    <div class=\"rowbox\">\r\n");
      out.write("                        <div class=\" span span100\">\r\n");
      out.write("                            <!-- 云服务器 -->\r\n");
      out.write("                            <div class=\"item-wrap ecs-wrap \">\r\n");
      out.write("                                <em class=\"item-icon\"></em>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>云服务器：<em class=\"text-big\" id=\"vmnum\">0</em></li>\r\n");
      out.write("                                    <li>&nbsp;&nbsp;&nbsp;试运行：<em id=\"resourcepilotrunnum\" class=\"text-big\">0</em></li>\r\n");
      out.write("                                    <li>开始计费：<em class=\"text-big\" id=\"resourcestartfeenum\">0</em></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"rowbox\">\r\n");
      out.write("                        <div class=\" span span50\">\r\n");
      out.write("                            <!-- 项目 -->\r\n");
      out.write("                            <div class=\"item-wrap project-wrap\">\r\n");
      out.write("                                <em class=\"item-icon\"></em>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>项目：<em class=\"text-big\" id=\"projectnum\">0</em></li>\r\n");
      out.write("                                    <li>应用：<em class=\"text-big\" id=\"appnum\">0</em></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\" span span50\" style=\"padding-left: 15px;\">\r\n");
      out.write("                            <!-- 告警 -->\r\n");
      out.write("                            <div class=\"item-wrap alarm-wrap\">\r\n");
      out.write("                                <em class=\"item-icon\"></em>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>故障：<em class=\"text-big\" id=\"breakdown\">0</em></li>\r\n");
      out.write("                                    <li>事件：<em class=\"text-big\" id=\"event\">0</em></li>\r\n");
      out.write("                                    <li>劣化：<em class=\"text-big\" id=\"degradation\">0</em></li>\r\n");
      out.write("                                    <li>通知：<em class=\"text-big\" id=\"notice\">0</em></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"rowbox\">\r\n");
      out.write("                <div class=\"span span66\">\r\n");
      out.write("                    <div class=\"item-wrap charging-wrap\"> <em class=\"item-icon\"></em>\r\n");
      out.write("                        <dl>\r\n");
      out.write("                            <dd id=\"yearfee\"><span id=\"yearfee\">0</span></dd>\r\n");
      out.write("                            <dt>当年费用</dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <dl>\r\n");
      out.write("                            <dd id=\"monthfee\"><span id=\"monthfee\">0</span></dd>\r\n");
      out.write("                            <dt>\r\n");
      out.write("                                当月费用\r\n");
      out.write("                            </dt>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"span span33\">\r\n");
      out.write("                    <!-- 通知公告 -->\r\n");
      out.write("                    <div class=\"item-wrap notice-wrap\">\r\n");
      out.write("                        <em class=\"item-icon\"></em>\r\n");
      out.write("                        <div class=\"text-big\" id=\"messagenum\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /web/../icp/include/taglib.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /web/../icp/include/taglib.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
