/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-11-09 03:06:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.systemMg;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class functionMgr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t.FieldInput2 {\r\n");
      out.write("\t\t\twidth:77%;\r\n");
      out.write("\t\t\theight:25px;\r\n");
      out.write("\t\t    background-color: #FFFFFF;\r\n");
      out.write("\t\t\tfont: normal 12px tahoma, arial, helvetica, sans-serif;\r\n");
      out.write("\t\t    text-align: left;\r\n");
      out.write("\t\t    word-wrap: break-word;\r\n");
      out.write("\t\t    padding-top:0px !important;\r\n");
      out.write("\t\t    padding-bottom:0px !important;\r\n");
      out.write("\t\t    border:#BCD2EE 1px solid !important;  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.FieldLabel2 {\r\n");
      out.write("\t\t\twidth:23%;\r\n");
      out.write("\t\t\theight:25px;\r\n");
      out.write("\t\t    background-color: #F0F8FF;\r\n");
      out.write("\t\t\tfont: normal 12px tahoma, arial, helvetica, sans-serif;\r\n");
      out.write("\t\t    text-align: left;\r\n");
      out.write("\t\t    word-wrap: break-word;\r\n");
      out.write("\t\t    padding-top:0px !important;\r\n");
      out.write("\t\t    padding-bottom:0px !important;\r\n");
      out.write("\t\t    padding-right:10px !important;\r\n");
      out.write("\t\t    border:#BCD2EE 1px solid !important;  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar toolbar = [{\r\n");
      out.write("\t\t\ttext:'增加',\r\n");
      out.write("\t\t\ticonCls:'icon-add',\r\n");
      out.write("\t\t\thandler:function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdebugger;\r\n");
      out.write("\t\t\t\t$(\"#fid\").val('');\r\n");
      out.write("\t\t\t\t$(\"#fname\").val('');\r\n");
      out.write("\t\t\t\t$(\"#hname\").val('#');\r\n");
      out.write("\t\t\t\t$(\"#fic\").val('default.png');\r\n");
      out.write("\t\t\t\t$(\"#isvalidcheck\").attr(\"checked\",true);\r\n");
      out.write("\t\t\t\t$(\"#isvalid\").val('1');\r\n");
      out.write("\t\t\t\t$('#w').window('open');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttext:'删除',\r\n");
      out.write("\t\t\ticonCls:'icon-remove',\r\n");
      out.write("\t\t\thandler:function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar rows = $('#dg').datagrid('getChecked');\r\n");
      out.write("\t\t\t\tif(rows.length<1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$.messager.alert('消息','请至少选择一条记录！'); \r\n");
      out.write("\t\t\t\t\treturn; \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(rows[0].fid){\r\n");
      out.write("\t\t\t\t\tvar fids = \"\";\r\n");
      out.write("\t\t\t\t\t $.each(rows,function(index,object){\r\n");
      out.write("\t\t\t\t\t \tfids+=object.fid+\",\";\r\n");
      out.write("\t   \t\t\t\t });\r\n");
      out.write("\t   \t\t\t\t $.messager.confirm('确认','您确认想要删除选中记录吗？',function(r){   \r\n");
      out.write("\t   \t\t\t\t  if (r){ \r\n");
      out.write("\t   \t\t\t\t  \t$.ajax({\r\n");
      out.write("\t   \t\t\t\t  \t\ttype : 'post',\r\n");
      out.write("\t   \t\t\t\t  \t\turl:urlrootpath+'/authMgr/delFunction.do',\r\n");
      out.write("\t   \t\t\t\t  \t\tdata:{fid:fids},\r\n");
      out.write("\t   \t\t\t\t  \t\tsuccess:function(retr){\r\n");
      out.write("\t   \t\t\t\t  \t\t\tvar data =  JSON.parse(retr); \r\n");
      out.write("\t   \t\t\t\t  \t\t\t$.messager.alert('消息',data.msg);  \r\n");
      out.write("\t\t\t\t\t  \t\t\tif(data.success)\r\n");
      out.write("\t\t\t\t\t\t    \t{\r\n");
      out.write("\t\t\t\t\t\t    \t\t$('#dg').datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t\t    \t\t$('#dg').datagrid('reload',icp.serializeObject($('#funcmgr_searchform')));\r\n");
      out.write("\t\t\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t\t\t\t    \t} \r\n");
      out.write("\t   \t\t\t\t  \t\t}\r\n");
      out.write("\t   \t\t\t\t  \t});\r\n");
      out.write("\t   \t\t\t\t  }\r\n");
      out.write("\t   \t\t\t\t });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttext:'修改',\r\n");
      out.write("\t\t\ticonCls:'icon-modify',\r\n");
      out.write("\t\t\thandler:function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdebugger;\r\n");
      out.write("\t\t\t\tvar rows = $('#dg').datagrid('getChecked');\r\n");
      out.write("\t\t\t\tif(rows.length!=1)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t$.messager.alert('消息','请选择一条记录！'); \r\n");
      out.write("\t\t\t\t\treturn; \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(rows[0].fid){\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#fid\").val(rows[0].fid);\r\n");
      out.write("\t\t\t\t\t$(\"#fname\").val(rows[0].fname);\r\n");
      out.write("\t\t\t\t\t$(\"#hname\").val(rows[0].hname);\r\n");
      out.write("\t\t\t\t\t$(\"#fic\").val(rows[0].fic);\r\n");
      out.write("\t\t\t\t\t$(\"#isvalidcheck\").attr(\"checked\",true);\r\n");
      out.write("\t\t\t\t\tif(rows[0].isvalid==1)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#isvalidcheck\").attr(\"checked\",true);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#isvalid\").val('1');\r\n");
      out.write("\t\t\t\t\t\t}else\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#isvalidcheck\").attr(\"checked\",false);\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#isvalid\").val('0');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$('#w').window('open');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t//$(\"#mm\").hide();\r\n");
      out.write("\t\t\tloadDataGrid();\r\n");
      out.write("\t\t\t//loadOrgTree();\r\n");
      out.write("\t\t\t//loadOrgTree(roleid);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction loadDataGrid()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$('#dg').datagrid({\r\n");
      out.write("\t\t\t\t\trownumbers:false,\r\n");
      out.write("\t\t\t\t\tborder:false,\r\n");
      out.write("\t\t\t\t\tstriped:true,\r\n");
      out.write("\t\t\t\t\tsortName:'fname',\r\n");
      out.write("\t\t\t\t\tsortOrder:'asc',\r\n");
      out.write("\t\t\t\t\tnowarp:false,\r\n");
      out.write("\t\t\t\t\tsingleSelect:false,\r\n");
      out.write("\t\t\t\t\tmethod:'post',\r\n");
      out.write("\t\t\t\t\tloadMsg:'数据装载中......',\r\n");
      out.write("\t\t\t\t\tfitColumns:true,\r\n");
      out.write("\t\t\t\t\tidField:'fid',\r\n");
      out.write("\t\t\t\t\tpagination:true,\r\n");
      out.write("\t\t\t\t\tpageSize:10,\r\n");
      out.write("\t\t\t\t\tpageList:[5,10,20,30,40,50],\r\n");
      out.write("\t\t\t\t\ttoolbar:toolbar,    \r\n");
      out.write("\t\t\t\t    url:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/authMgr/getAllFunction.do',\r\n");
      out.write("\t\t\t\t    onLoadSuccess: function (data) {\r\n");
      out.write("\t\t\t\t\t      var pageopt = $('#dg').datagrid('getPager').data(\"pagination\").options;\r\n");
      out.write("\t\t\t\t\t      var  _pageSize = pageopt.pageSize;\r\n");
      out.write("\t\t\t\t\t      var  _rows = $('#dg').datagrid(\"getRows\").length\r\n");
      out.write("\t\t\t\t\t      if (_pageSize >= 10) {\r\n");
      out.write("\t\t\t\t\t         for(i=10;i>_rows;i--){\r\n");
      out.write("\t\t\t\t\t            //添加一个新数据行，其中{} 中的operation 为最后一列 的列名 如下图说明\r\n");
      out.write("\t\t\t\t\t            $(this).datagrid('appendRow', {operation:''  })\r\n");
      out.write("\t\t\t\t\t         }\r\n");
      out.write("\t\t\t\t\t         // $(this).closest('div.datagrid-wrap').find('div.datagrid-pager').hide();\r\n");
      out.write("\t\t\t\t\t      }else{\r\n");
      out.write("\t\t\t\t\t         //如果通过调用reload方法重新加载数据有数据时显示出分页导航容器\r\n");
      out.write("\t\t\t\t\t         $(this).closest('div.datagrid-wrap').find('div.datagrid-pager').show();\r\n");
      out.write("\t\t\t\t\t      }\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tfunction searchDataGrid(){\r\n");
      out.write("\t\t\t$('#dg').datagrid('load',icp.serializeObject($('#funcmgr_searchform')));\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tfunction statusformater(value,row,index)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t\tswitch (value) {\r\n");
      out.write("\t\t\t\t\t\t\tcase 1:\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<span style=\\\"color:green\\\">在用</span>\";\r\n");
      out.write("\t\t\t\t\t\t\tcase 0:\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"<span style=\\\"color:red\\\">停用</span>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t function submitSave()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t \t$('#tableform').form('submit',{\r\n");
      out.write("\t\t    url:urlrootpath+'/authMgr/addorupdateFunction.do', \r\n");
      out.write("\t\t    onSubmit: function(){\r\n");
      out.write("\t\t    \tif($(\"#fname\").attr(\"value\")==null || $.trim($(\"#fname\").attr(\"value\"))==\"\" )\r\n");
      out.write("\t\t    \t{\r\n");
      out.write("\t\t    \t\t$.messager.alert('消息',\"功能名称不能为空!\");  \r\n");
      out.write("\t\t    \t\treturn false;\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \tif($(\"#hname\").attr(\"value\")==null || $.trim($(\"#hname\").attr(\"value\"))==\"\" )\r\n");
      out.write("\t\t    \t{\r\n");
      out.write("\t\t    \t\t$.messager.alert('消息',\"URL不能为空!\");  \r\n");
      out.write("\t\t    \t\treturn false;\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \t$(\"#isvalid\").val($(\"#isvalidcheck\").attr(\"checked\")?1:0);\r\n");
      out.write("\t\t    \t$(\"#ename\").val( $(\"#fname\").attr(\"value\"));\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t    success:function(retr){\r\n");
      out.write("\t\t    \t//$.messager.progress('close');\t// 如果表单是无效的则隐藏进度条\r\n");
      out.write("\t\t    \tvar _data =  JSON.parse(retr); \r\n");
      out.write("\t\t    \t//alert(\"success: \"+_data.success);\r\n");
      out.write("\t\t    \t$.messager.alert('消息',_data.msg);  \r\n");
      out.write("\t\t\t\tif(_data.success){\r\n");
      out.write("\t\t\t\t\t$('#dg').datagrid('reload',icp.serializeObject($('#funcmgr_searchform')));\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t \t$('#w').window('close');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"easyui-layout\" data-options=\"fit:true,border:false\" style=\"padding:10px 20px 10px 20px;margin:10px 20px 10px 20px;\">\r\n");
      out.write("\t\t<div data-options=\"region:'north',border:false\" style=\"background:#eee;height:30px;width:100%;overflow:hidden;\">\r\n");
      out.write("\t\t\t<form id=\"funcmgr_searchform\">\r\n");
      out.write("\t\t\t\t<tr  class=\"tableForm datagrid-toolbar\">\r\n");
      out.write("\t\t\t\t\t<td>功能名称：<input class=\"easyui-textbox\" name=\"fname\"  id=\"searchfname\" style=\"width:200px;height:30px;border:false\"></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;状态：<select  id=\"searchisvalid\" class=\"easyui-combobox\" name=\"isvalid\" data-options=\"panelHeight:'auto',required:true,editable:false\" style=\"width:120px;height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\" selected>全部</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">在用</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">停用</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search',plain:true\" onclick=\"searchDataGrid()\">查询</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-redo',plain:true\" onclick=\"$('#funcmgr_searchform input').val('');$('#searchfname').textbox('clear');$('#searchisvalid').combobox('select', 2);$('#dg').datagrid('load',{});\">重置</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'center',border:false\">\r\n");
      out.write("\t\t\t<table title=\"\" style=\"width:100%;\"  id=\"dg\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'ck',checkbox:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'fid',hidden:true\"></th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'fname',width:120,align:'center',sortable:true\">功能名称</th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'hname',width:200,align:'center'\">URL</th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'fic',width:200,align:'center'\">前置图标</th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'isvalid',width:80,align:'center',formatter:statusformater\">状态</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"w\" class=\"easyui-window\" title=\"功能项维护\" data-options=\"closed:true,iconCls:'icon-save',inline:true\" style=\"width:500px;height:220px;padding:5px;\">\r\n");
      out.write("\t\t\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'center'\" style=\"padding:10px;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"tableform\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"fid\" name=\"fid\" type=\"hidden\"  />\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"appid\" name=\"appid\"  type=\"hidden\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"ename\" name=\"ename\"  type=\"hidden\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"isvalid\" name=\"isvalid\"  type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t\t<table align=\"center\"  style=\"width:80%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldLabel2\" style=\"border-top:!important;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t功能名称：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldInput2\"><input id=\"fname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height:25px\" name=\"fname\" class=\"easyui-validatebox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"required:true\" /><font color=\"red\">*</font></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldLabel2\">URL：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldInput2\"><input id=\"hname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height:25px\" name=\"hname\" class=\"easyui-validatebox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"required:true\" value=\"#\" /><font color=\"red\">*（相对路径）</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldLabel2\">前置图标：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldInput2\"><input id=\"fic\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height:25px\" name=\"fic\" class=\"easyui-validatebox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-options=\"required:true\" value=\"default.png\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldLabel2\">是否有效：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"FieldInput2\"><input id=\"isvalidcheck\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"checkbox\" checked=\"checked\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'south',border:false\" style=\"text-align:right;padding:5px 0 0;\">\r\n");
      out.write("\t\t\t\t\t<a class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-ok'\" href=\"javascript:void(0)\" onclick=\"submitSave();\" style=\"width:80px\">确定</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" href=\"javascript:void(0)\" onclick=\"$('#w').window('close');\" style=\"width:80px\">取消</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
