/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-11-09 03:06:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.systemMg;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.inspur.icpmg.util.WebLevelUtil;
import com.inspur.icpmg.systemMg.vo.UserEntity;

public final class roleMgr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String contextPath = request.getContextPath();
      out.write('\r');
      out.write('\n');

	String muser = null;
	UserEntity ue = WebLevelUtil.getUser(request);
	if(ue != null){
		if(ue.getAlias() != null){
			muser = ue.getAlias();
		}else{
			muser = ue.getEmail();
		}
	}

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.tableForm{\r\n");
      out.write("\t}\r\n");
      out.write("\t.tableForm th{\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tableForm td input{\r\n");
      out.write("\t\twidth:150px;\r\n");
      out.write("\t\ttext-align:left;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("icp.ns('icp.admin.role');\r\n");
      out.write("$(function(){\r\n");
      out.write("\ticp.admin.role.searchForm = $('#rolemgr_searchform').form();\r\n");
      out.write("\tvar roletype_data = [{\"value\":\"1\",\"text\":\"实角色\"},{\"value\":\"0\",\"text\":\"虚角色\"}];\r\n");
      out.write("\tvar usertype_data = [{\"value\":\"1\",\"text\":\"超级用户\"},{\"value\":\"2\",\"text\":\"普通用户\"}];\r\n");
      out.write("\tvar datalevel_data = [{\"value\":\"1\",\"text\":\"资源\"},{\"value\":\"2\",\"text\":\"机房\"},{\"value\":\"3\",\"text\":\"地市\"},{\"value\":\"4\",\"text\":\"省\"},{\"value\":\"5\",\"text\":\"节点\"},\r\n");
      out.write("\t\t{\"value\":\"6\",\"text\":\"子帐号\"},{\"value\":\"7\",\"text\":\"父帐号\"},{\"value\":\"8\",\"text\":\"角色\"},{\"value\":\"9\",\"text\":\"全部\"}];\r\n");
      out.write("\tvar isvalid_data = [{\"value\":\"1\",\"text\":\"在用\"},{\"value\":\"0\",\"text\":\"停用\"}];\r\n");
      out.write("\t\r\n");
      out.write("\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\ticp.admin.role.datagrid = $('#datagrid_role').datagrid({\r\n");
      out.write("\t\turl:'");
      out.print(contextPath);
      out.write("/authMgr/getRoles.do',\r\n");
      out.write("\t\ttitle:'',\r\n");
      out.write("\t\ticonCls:'icon-save',\r\n");
      out.write("\t\tpagination:true,\r\n");
      out.write("\t\tpageSize:10,\r\n");
      out.write("\t\tpageList:[5,10,20,30,40,50],\r\n");
      out.write("\t\t/* fit:true, */\r\n");
      out.write("\t\tfitColumns:true,\r\n");
      out.write("\t\tnowarp:false,\r\n");
      out.write("\t\tborder:false,\r\n");
      out.write("\t\tscrollbarSize:0,\r\n");
      out.write("\t\tidField:'roleid',\r\n");
      out.write("\t\tsortName:'rolename',\r\n");
      out.write("\t\tsortOrder:'asc',\r\n");
      out.write("\t\tfrozenColumns:[[ \r\n");
      out.write("\t\t\t{field:'ck',checkbox:true} \r\n");
      out.write("\t\t]],\r\n");
      out.write("\t\tcolumns:[[{\r\n");
      out.write("\t\t\ttitle:'角色编码',\r\n");
      out.write("\t\t\tfield:'roleid',\r\n");
      out.write("\t\t\thidden:true,\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'角色名称',\r\n");
      out.write("\t\t\tfield:'rolename',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tsortable:true,\r\n");
      out.write("\t\t\teditor:{\r\n");
      out.write("\t\t\t\ttype:'validatebox',\r\n");
      out.write("\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\trequired:true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'角色类型',\r\n");
      out.write("\t\t\tfield:'roletype',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t    for(var i = 0; i < roletype_data.length; i++){\r\n");
      out.write("\t\t\t        if (roletype_data[i].value == value){\r\n");
      out.write("\t\t\t            return roletype_data[i].text;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditor:{\r\n");
      out.write("\t\t\t\ttype:'combobox',\r\n");
      out.write("\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\trequired:true,\r\n");
      out.write("\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\tdata:roletype_data,\r\n");
      out.write("\t\t\t\t\tvalueField:\"value\",\r\n");
      out.write("\t\t\t\t\ttextField:\"text\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'操作权限',\r\n");
      out.write("\t\t\tfield:'usertype',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t    for(var i = 0; i < usertype_data.length; i++){\r\n");
      out.write("\t\t\t        if (usertype_data[i].value == value){\r\n");
      out.write("\t\t\t            return usertype_data[i].text;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditor:{\r\n");
      out.write("\t\t\t\ttype:'combobox',\r\n");
      out.write("\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\trequired:true,\r\n");
      out.write("\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\tdata:usertype_data,\r\n");
      out.write("\t\t\t\t\tvalueField:\"value\",\r\n");
      out.write("\t\t\t\t\ttextField:\"text\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'数据权限',\r\n");
      out.write("\t\t\tfield:'datalevel',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t    for(var i = 0; i < datalevel_data.length; i++){\r\n");
      out.write("\t\t\t        if (datalevel_data[i].value == value){\r\n");
      out.write("\t\t\t            return datalevel_data[i].text;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditor:{\r\n");
      out.write("\t\t\t\ttype:'combobox',\r\n");
      out.write("\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\trequired:true,\r\n");
      out.write("\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\tdata: datalevel_data,\r\n");
      out.write("\t\t\t\t\tvalueField: \"value\",\r\n");
      out.write("\t\t\t\t\ttextField: \"text\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'接口权限',\r\n");
      out.write("\t\t\tfield:'apitype',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t\tif(value){\r\n");
      out.write("\t\t\t\t\tvar arrApitype = value.split(',');\r\n");
      out.write("\t\t\t\t\tvar apitypeText = '';\r\n");
      out.write("\t\t\t\t\tfor(var i=0; i < arrApitype.length; i++){\r\n");
      out.write("\t\t\t\t\t\tif(arrApitype[i] == '1'){\r\n");
      out.write("\t\t\t\t\t\t\tapitypeText = apitypeText+'资源查询类,';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(arrApitype[i] == '2'){\r\n");
      out.write("\t\t\t\t\t\t\tapitypeText = apitypeText+'指标查询类,';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(arrApitype[i] == '3'){\r\n");
      out.write("\t\t\t\t\t\t\tapitypeText = apitypeText+'设备操作类';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(apitypeText[apitypeText.length-1] == ','){\r\n");
      out.write("\t\t\t\t\t\treturn apitypeText.substring(0, apitypeText.length-1);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t    return apitypeText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditor:{\r\n");
      out.write("\t\t\t\ttype:'combotree',\r\n");
      out.write("\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/systemMg/apitype_data.json',\r\n");
      out.write("\t\t\t\t\trequired:true,\r\n");
      out.write("\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\tmultiple:true\r\n");
      out.write("\t\t\t\t\t/* valueField:\"id\",\r\n");
      out.write("\t\t\t\t\ttextField:\"text\" */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'状态',\r\n");
      out.write("\t\t\tfield:'isvalid',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tformatter:function(value,row,index){\r\n");
      out.write("\t\t\t    for(var i = 0; i < isvalid_data.length; i++){\r\n");
      out.write("\t\t\t        if (isvalid_data[i].value == value){\r\n");
      out.write("\t\t\t            return isvalid_data[i].text;\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditor:{\r\n");
      out.write("\t\t\t\ttype:'combobox',\r\n");
      out.write("\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\trequired:true,\r\n");
      out.write("\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\tdata:isvalid_data,\r\n");
      out.write("\t\t\t\t\tvalueField: \"value\",\r\n");
      out.write("\t\t\t\t\ttextField: \"text\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'修改人',\r\n");
      out.write("\t\t\tfield:'muser',\r\n");
      out.write("\t\t\twidth:100\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'修改时间',\r\n");
      out.write("\t\t\tfield:'mtime',\r\n");
      out.write("\t\t\twidth:120\r\n");
      out.write("\t\t},{\r\n");
      out.write("\t\t\ttitle:'操作',\r\n");
      out.write("\t\t\tfield:'ops',\r\n");
      out.write("\t\t\twidth:100,\r\n");
      out.write("\t\t\tformatter: function(value,rowData,rowIndex){\r\n");
      out.write("\t\t\t\tif(rowData.roleid){\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar str='';\r\n");
      out.write("\t\t\t\t\tstr += '<a onclick=\"icp.admin.role.role_showLogFun('+rowData.roleid+');\">日志</a>|';\r\n");
      out.write("\t\t\t\t\tstr += '<a onclick=\"icp.admin.role.role_showAllUsersFun('+rowData.roleid+');\">用户</a>';\r\n");
      out.write("\t\t\t\t\treturn str;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}]],\r\n");
      out.write("\t\ttoolbar:'#role_tb',\r\n");
      out.write("\t\tonAfterEdit:function(rowIndex,rowData,changes){\r\n");
      out.write("\t\t\tvar inserted = icp.admin.role.datagrid.datagrid('getChanges','inserted');\r\n");
      out.write("\t\t\tvar updated = icp.admin.role.datagrid.datagrid('getChanges','updated');\t\r\n");
      out.write("\t\t\tif(inserted < 1 && updated < 1){\r\n");
      out.write("\t\t\t\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\t\t\t\ticp.admin.role.datagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar url = '';\r\n");
      out.write("\t\t\tif(inserted.length > 0){\r\n");
      out.write("\t\t\t\turl = '");
      out.print(contextPath);
      out.write("/authMgr/addRole.do';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(updated.length > 0){\r\n");
      out.write("\t\t\t\turl = '");
      out.print(contextPath);
      out.write("/authMgr/editRole.do';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(inserted.length <= 0 && updated.length <= 0){\r\n");
      out.write("\t\t\t\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\t\t\t\ticp.admin.role.datagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:url,\r\n");
      out.write("\t\t\t\tdata:rowData,\r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\tsuccess:function(r){\r\n");
      out.write("\t\t\t\t\tif(r && r.success){\r\n");
      out.write("\t\t\t\t\t\ticp.admin.role.datagrid.datagrid('acceptChanges');\r\n");
      out.write("\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\tmsg:r.msg,\r\n");
      out.write("\t\t\t\t\t\t\ttitle:'成功'\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\ticp.admin.role.datagrid.datagrid('rejectChanges');\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert('错误',r.msg,'error');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\t\t\t\t\ticp.admin.role.datagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\ticp.admin.role.datagrid.datagrid('reload');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonDblClickRow:function(rowIndex,rowData){\r\n");
      out.write("\t\t\t/* icp.admin.role.datagrid.datagrid('removeEditor','roleid'); */\r\n");
      out.write("\t\t\tif(icp.admin.role.editRow != undefined){\r\n");
      out.write("\t\t\t\ticp.admin.role.datagrid.datagrid('endEdit',icp.admin.role.editRow);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(icp.admin.role.editRow == undefined){\r\n");
      out.write("\t\t\t\ticp.admin.role.datagrid.datagrid('beginEdit',rowIndex);\t\r\n");
      out.write("\t\t\t\ticp.admin.role.editRow=rowIndex;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonLoadSuccess: function (data) {\r\n");
      out.write("\t\t      var pageopt = $('#datagrid_role').datagrid('getPager').data(\"pagination\").options;\r\n");
      out.write("\t\t      var  _pageSize = pageopt.pageSize;\r\n");
      out.write("\t\t      var  _rows = $('#datagrid_role').datagrid(\"getRows\").length\r\n");
      out.write("\t\t      if (_pageSize >= 10) {\r\n");
      out.write("\t\t         for(i=10;i>_rows;i--){\r\n");
      out.write("\t\t            //添加一个新数据行，其中{} 中的operation 为最后一列 的列名 如下图说明\r\n");
      out.write("\t\t            $(this).datagrid('appendRow', {operation:''  })\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t         // $(this).closest('div.datagrid-wrap').find('div.datagrid-pager').hide();\r\n");
      out.write("\t\t      }else{\r\n");
      out.write("\t\t         //如果通过调用reload方法重新加载数据有数据时显示出分页导航容器\r\n");
      out.write("\t\t         $(this).closest('div.datagrid-wrap').find('div.datagrid-pager').show();\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t});\r\n");
      out.write("\ticp.admin.role.searchFun=function(){\r\n");
      out.write("\t\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\t\ticp.admin.role.datagrid.datagrid('load',icp.serializeObject(icp.admin.role.searchForm));\r\n");
      out.write("\t};\r\n");
      out.write("\ticp.admin.role.cleanSearchFun=function(){\r\n");
      out.write("\t\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\t\ticp.admin.role.searchForm.find('input').val('');\r\n");
      out.write("\t\ticp.admin.role.datagrid.datagrid('load',{});\r\n");
      out.write("\t};\r\n");
      out.write("});\r\n");
      out.write("icp.admin.role.addRoleFun=function(){\r\n");
      out.write("\tif(icp.admin.role.editRow != undefined){\r\n");
      out.write("\t\ticp.admin.role.datagrid.datagrid('endEdit',icp.admin.role.editRow);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(icp.admin.role.editRow == undefined){\r\n");
      out.write("\t\tvar row = {\r\n");
      out.write("\t\t\tmuser:'");
      out.print(muser);
      out.write("'\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\ticp.admin.role.datagrid.datagrid('insertRow',{\r\n");
      out.write("\t\t\tindex:0,\r\n");
      out.write("\t\t\trow:row\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ticp.admin.role.datagrid.datagrid('beginEdit',0);\t\r\n");
      out.write("\t\ticp.admin.role.editRow=0;\r\n");
      out.write("\t}\r\n");
      out.write("};\r\n");
      out.write("icp.admin.role.delRoleFun=function(){\r\n");
      out.write("\tvar rows = icp.admin.role.datagrid.datagrid('getSelections');\r\n");
      out.write("\tif(rows.length > 0){\r\n");
      out.write("\t\t$.messager.confirm('请确认','要删除【'+rows.length+'】项，确定要删除吗?',function(b){\r\n");
      out.write("\t\t\tif(b){\r\n");
      out.write("\t\t\t\tvar ids = [];\r\n");
      out.write("\t\t\t\tvar idsName = [];\r\n");
      out.write("\t\t\t\tfor(var i =0;i<rows.length;i++){\r\n");
      out.write("\t\t\t\t\tids.push(rows[i].roleid);\r\n");
      out.write("\t\t\t\t\tidsName.push(rows[i].rolename);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:'");
      out.print(contextPath);
      out.write("/authMgr/deleteRole.do',\r\n");
      out.write("\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\tdelroleids: ids.join(','),\r\n");
      out.write("\t\t\t\t\t\tdelrolesName:idsName.join(',')\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tcache:false,\r\n");
      out.write("\t\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(r){\r\n");
      out.write("\t\t\t\t\t\tif(r && r.success){\r\n");
      out.write("\t\t\t\t\t\t\ticp.admin.role.datagrid.datagrid('acceptChanges');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\t\t\tmsg:r.msg,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle:'成功'\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\ticp.admin.role.datagrid.datagrid('rejectChanges');\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert('错误',r.msg,'error');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\ticp.admin.role.datagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t\t\ticp.admin.role.datagrid.datagrid('load');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.messager.alert('提示','请选择要删除的角色！','error');\r\n");
      out.write("\t}\r\n");
      out.write("};\r\n");
      out.write("icp.admin.role.editRoleFun=function(){\r\n");
      out.write("\tvar rows = icp.admin.role.datagrid.datagrid('getSelections');\r\n");
      out.write("\tif(rows.length == 1){\r\n");
      out.write("\t\tif(icp.admin.role.editRow != undefined){\r\n");
      out.write("\t\t\ticp.admin.role.datagrid.datagrid('endEdit',icp.admin.role.editRow);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(icp.admin.role.editRow == undefined){\r\n");
      out.write("\t\t\tvar index = icp.admin.role.datagrid.datagrid('getRowIndex',rows[0]);\t\r\n");
      out.write("\t\t\ticp.admin.role.datagrid.datagrid('beginEdit',index);\t\r\n");
      out.write("\t\t\ticp.admin.role.editRow=index;\r\n");
      out.write("\t\t\ticp.admin.role.datagrid.datagrid('unselectAll');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.messager.alert('提示','请选择一个角色修改！','error');\r\n");
      out.write("\t}\r\n");
      out.write("};\r\n");
      out.write("icp.admin.role.saveRoleFun=function(){\r\n");
      out.write("\ticp.admin.role.datagrid.datagrid('endEdit',icp.admin.role.editRow);\r\n");
      out.write("};\r\n");
      out.write("icp.admin.role.redoRoleFun=function(){\r\n");
      out.write("\ticp.admin.role.editRow = undefined;\r\n");
      out.write("\ticp.admin.role.datagrid.datagrid('rejectChanges');\r\n");
      out.write("\ticp.admin.role.datagrid.datagrid('unselectAll');\r\n");
      out.write("};\r\n");
      out.write("icp.admin.role.role_showAllUsersFun=function(role_id){\r\n");
      out.write("\tvar dialog = parent.icp.modalDialog({\r\n");
      out.write("\t\ttitle : '角色对应的所有用户',\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/systemMg/roleMgrAllUsers.jsp?id=' + role_id\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("icp.admin.role.role_showLogFun=function(roleid){\r\n");
      out.write("\tvar dialog = parent.icp.modalDialog({\r\n");
      out.write("\t\ttitle : '角色日志',\r\n");
      out.write("\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/systemMg/roleAllOperaLog.jsp?id=' + roleid\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"easyui-layout\" data-options=\"fit:true,border:false\" style=\"padding:10px 20px 10px 20px;margin:10px 20px 10px 20px;\">\r\n");
      out.write("\t<div data-options=\"region:'north',border:false\" style=\"background:#eee;width:100%;height:30px;overflow:hidden;border:false\">\r\n");
      out.write("\t\t<form id=\"rolemgr_searchform\">\r\n");
      out.write("\t\t\t<tr class=\"tableForm datagrid-toolbar\">\r\n");
      out.write("\t\t\t\t<td>角色：<input class=\"easyui-textbox\" id=\"rolename\" name=\"roleSearch\" style=\"width:110px;height:30px;border:false\"></td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;状态：<select class=\"easyui-combobox\" name=\"status\" id=\"status\" data-options=\"panelHeight:'auto',required:true,editable:false\" style=\"width:100px;height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">全部</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">在用</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">停用</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>&nbsp;&nbsp;<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search',plain:true\" onclick=\"icp.admin.role.searchFun()\">查询</a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-redo',plain:true\" onclick=\"icp.admin.role.cleanSearchFun();$('#rolename').textbox('clear');$('#status').combobox('select','2');\">重置</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'center',border:false\">\r\n");
      out.write("\t\t<table id=\"datagrid_role\" style=\"background:#eee;overflow:hidden;width:100%;\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"role_tb\" style=\"background:#f4f4f4;width:100%;float:left\">\r\n");
      out.write("\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save',plain:true\" onclick=\"icp.admin.role.saveRoleFun()\">保存</a>\r\n");
      out.write("\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',plain:true\" onclick=\"icp.admin.role.addRoleFun()\">增加</a>\r\n");
      out.write("\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-edit',plain:true\" onclick=\"icp.admin.role.editRoleFun()\">修改</a>\r\n");
      out.write("\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-remove',plain:true\" onclick=\"icp.admin.role.delRoleFun()\">删除</a>\r\n");
      out.write("\t<a href=\"javascript:void(0);\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-redo',plain:true\" onclick=\"icp.admin.role.redoRoleFun()\">取消编辑</a>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
