/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2016-11-09 07:07:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.osdeploy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class environMg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/icp/include/taglib.jsp", Long.valueOf(1478489851195L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar content =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/osdeploy/css/osdeploy.css\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/osdeploy/js/util.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/sockjs-0.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var ws = null;\r\n");
      out.write("var url = null;\r\n");
      out.write("var transports = [];\r\n");
      out.write("var scrollIndex=0;\r\n");
      out.write("var canbeinit =true;\r\n");
      out.write("$(function() {\r\n");
      out.write("    updateUrl('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/sockjs/echo');\r\n");
      out.write("    connect();\r\n");
      out.write("});\r\n");
      out.write("//更新环境信息\r\n");
      out.write("function queryEnviron() {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"GET\",\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryEnviron.do\",\r\n");
      out.write("        async: true,\r\n");
      out.write("        data: {\r\n");
      out.write("            environId: $(\"#environId\").val()\r\n");
      out.write("        },\r\n");
      out.write("        success: function(data) {\r\n");
      out.write("            if (data) {\r\n");
      out.write("//                 $(\"#ctime\").text(\"创建于\" + data.ctime.substring(0, 10));\r\n");
      out.write("                $(\"#controlnum\").text(data.controlnum);\r\n");
      out.write("                $(\"#computenum\").text(data.computenum);\r\n");
      out.write("                $(\"#storagenum\").text(data.storagenum);\r\n");
      out.write("                $(\"#env_status\").val(data.status);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("// contype|comtype|stgtype\r\n");
      out.write("// 打开节点窗口\r\n");
      out.write("function showNodeDg(nodeType) {\r\n");
      out.write(" //   console.log(nodeType);\r\n");
      out.write("    $('#node_dialog').dialog('open');\r\n");
      out.write("    $(\"#nodeType\").val(nodeType);\r\n");
      out.write("    if (nodeType === 'contype') {\r\n");
      out.write("        $('#node_dialog').panel({\r\n");
      out.write("            title: '分配控制节点'\r\n");
      out.write("        });\r\n");
      out.write("    } else if (nodeType === 'comtype') {\r\n");
      out.write("        $('#node_dialog').panel({\r\n");
      out.write("            title: '分配计算节点'\r\n");
      out.write("        });\r\n");
      out.write("    } else if (nodeType === 'stgtype') {\r\n");
      out.write("        $('#node_dialog').panel({\r\n");
      out.write("            title: '分配存储节点'\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    $('#node_dg').datagrid({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryNodeType.do',\r\n");
      out.write("        queryParams: {\r\n");
      out.write("            nodeType: nodeType,\r\n");
      out.write("            environid:$(\"#environId\").val(),\r\n");
      out.write("            isNode:1\r\n");
      out.write("        },\r\n");
      out.write("        method: 'post',\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("// contype|comtype|stgtype\r\n");
      out.write("//添加节点窗口\r\n");
      out.write("function showAddNodeDg() {\r\n");
      out.write("    $('#node_dialog').dialog('close');\r\n");
      out.write("    $('#add_node_dialog').dialog('open');\r\n");
      out.write("    var nodeType =$('#nodeType').val();\r\n");
      out.write("    $('#add_node_dg').datagrid({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryNodeType.do',\r\n");
      out.write("        queryParams: {\r\n");
      out.write("            nodeType: nodeType,\r\n");
      out.write("            environId:$(\"#environId\").val(),\r\n");
      out.write("            isNode:0\r\n");
      out.write("        },\r\n");
      out.write("        method: 'post',\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//打开添加主机对话框，展示非本环境物理机列表\r\n");
      out.write("function showAddHostDg(){\r\n");
      out.write("\t$('#add_host_dialog').dialog('open');\r\n");
      out.write("\t$('#add_host_dg').datagrid({\r\n");
      out.write("        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryHosts.do',\r\n");
      out.write("        queryParams: {\r\n");
      out.write("           \tisEnviron:'0',\r\n");
      out.write("            environId:$(\"#environId\").val(),\r\n");
      out.write("        },\r\n");
      out.write("        method: 'post',\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//主机状态\r\n");
      out.write("// function configConNode() {\r\n");
      out.write("//     loadMask(\"为控制节点进行【环境初始化】，请稍后...\");\r\n");
      out.write("//     $.ajax({\r\n");
      out.write("//         type: \"GET\",\r\n");
      out.write("//         dataType: \"json\",\r\n");
      out.write("//         url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/configConNode.do\",\r\n");
      out.write("//         async: true,\r\n");
      out.write("//         data: {\r\n");
      out.write("//             hostId: hostId,\r\n");
      out.write("//             ipAddr: ipAddr\r\n");
      out.write("//         },\r\n");
      out.write("//         success: function(data) {\r\n");
      out.write("//             if (data.success) {\r\n");
      out.write("//                 $.messager.alert('消息', data.msg, 'info');\r\n");
      out.write("//             } else {\r\n");
      out.write("//                 $.messager.alert('错误', data.msg, 'error');\r\n");
      out.write("//             }\r\n");
      out.write("//             disLoad();\r\n");
      out.write("//             $('#compute_node').datagrid('reload');\r\n");
      out.write("//         }\r\n");
      out.write("//     });\r\n");
      out.write("// }\r\n");
      out.write("\r\n");
      out.write("function updateUrl(urlPath) {\r\n");
      out.write("    if (urlPath.indexOf('sockjs') != -1) {\r\n");
      out.write("        url = urlPath;\r\n");
      out.write("    } else {\r\n");
      out.write("        if (window.location.protocol == 'http:') {\r\n");
      out.write("            url = 'ws://' + window.location.host + urlPath;\r\n");
      out.write("        } else {\r\n");
      out.write("            url = 'wss://' + window.location.host + urlPath;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function connect() {\r\n");
      out.write("\tif(os_deploy_ws){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("    if (!url) {\r\n");
      out.write("        alert('Select whether to use W3C WebSocket or SockJS');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    os_deploy_ws = (url.indexOf('sockjs') != -1) ? new SockJS(url, undefined, {\r\n");
      out.write("        protocols_whitelist: transports\r\n");
      out.write("    }) : new WebSocket(url);\r\n");
      out.write("    os_deploy_ws.onopen = function() {};\r\n");
      out.write("    os_deploy_ws.onmessage = function(event) {\r\n");
      out.write("        var msg = event.data;\r\n");
      out.write("        $('#operate_log').datagrid('appendRow',{\r\n");
      out.write("        \ttime:msg.split(\",\")[0],\r\n");
      out.write("        \tip:msg.split(\",\")[1],\r\n");
      out.write("        \tevent:msg.split(\",\")[2],\r\n");
      out.write("        \tresult:(msg.split(\",\")[3]=='1'?\"成功\":\"失败\")\r\n");
      out.write("        });\r\n");
      out.write("        debugger;\r\n");
      out.write("        $('#operate_log').datagrid('scrollTo',scrollIndex);\r\n");
      out.write("        scrollIndex++;\r\n");
      out.write("    };\r\n");
      out.write("    os_deploy_ws.onclose = function(event) {};\r\n");
      out.write("}\r\n");
      out.write("//查询某一状态下环境内设备\r\n");
      out.write("function queryByStatus(status) {\r\n");
      out.write("    var a = [];\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryByStatus.do\",\r\n");
      out.write("        async: false,\r\n");
      out.write("        data: {\r\n");
      out.write("            status: status,\r\n");
      out.write("            environId: $(\"#environId\").val()\r\n");
      out.write("        },\r\n");
      out.write("        success: function(data) {\r\n");
      out.write("            a = data;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    return a;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"easyui-layout\" data-options=\"fit:true,border:false\"\r\n");
      out.write("\tstyle=\"padding:10px 20px 50px 20px;margin:10px 20px 30px 20px;\">\r\n");
      out.write("\t<div data-options=\"region:'north',border:false\"\r\n");
      out.write("\t\tstyle=\"height:290px;overflow:hidden;background-color: #eee\">\r\n");
      out.write("\t\t<div class=\"kvm-layout-left\">\r\n");
      out.write("\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t<span class=\"title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.environname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span> <span class=\"date\">创建于:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(OsDeployEnvironVo.ctime, 0, 10)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
      out.write("</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"body\">\r\n");
      out.write("\t\t\t\t<li><i class=\"kvm-icon icon-kz\"></i>控制 <em id=\"controlnum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.controlnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</em></li>\r\n");
      out.write("\t\t\t\t<li><i class=\"kvm-icon icon-js\"></i>计算 <em id=\"computenum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.computenum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</em></li>\r\n");
      out.write("\t\t\t\t<li><i class=\"kvm-icon icon-cc\"></i>存储 <em id=\"storagenum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.storagenum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</em></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"kvm-layout-right\">\r\n");
      out.write("\t\t\t<ul class=\"kvm-step\" id=\"stepTab\">\r\n");
      out.write("\t\t\t\t<li class=\"step1 active\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"quan\">1</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">资源选择</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"step2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"quan\">2</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">安装前配置检查</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"step3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"quan\">3</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">执行安装</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"step4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"quan\">4</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">资源配置</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"j-main\">\r\n");
      out.write("\t\t\t\t<div class=\"body\" id=\"step1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">请点击以下节点进行资源选择：</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kvm-btn-box\" onclick=\"showAddNode('conType')\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-kz\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon \"></i>控制节点\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"select\">选择</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kvm-btn-box\" onclick=\"showAddNode('comType')\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-js\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon\"></i>计算节点\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"select\">选择</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kvm-btn-box\" onclick=\"showAddNode('stgType')\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-cc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon \"></i>存储节点\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"select\">选择</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"kvm-footer\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"kvm-ts\"></i> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-linkbutton\" onclick=\"goStep(2)\">下一步 &gt;</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"body kvm-pzjc\" id=\"step2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">安装前检查以下配置：</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kvm-btn-box active\" id=\"kvmWlpz\" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-wlpz\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon \"></i>网络配置\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"select\" id=\"net-icon\">");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kvm-icon-arrow\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"kvmSfqpz\" ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" onclick=\"checkServer('#server-icon')\"\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-fwqpz\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon \"></i>服务器配置\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"select\" id=\"server-icon\">");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"kvm-footer\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"goStep(1)\">&lt;\r\n");
      out.write("\t\t\t\t\t\t\t上一步 </a> <a href=\"#\" class=\"easyui-linkbutton\" onclick=\"goStep(3)\">下一步&gt;</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"body \" id=\"step3\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">安装列表</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"kvm-set\">\r\n");
      out.write("\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t控制节点\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"kvm-set-os\" id =\"con_icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"kvm-ok\" ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" ");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-options=\"iconCls:'icon-objopen',plain:true\" onclick=\"installWare('#con_icon','conType')\">安装</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd id=\"con_install\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t计算节点<!--style=\"display: none\"  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"kvm-set-os\" id =\"com_icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"kvm-ok\" ");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" ");
      if (_jspx_meth_c_005fif_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-options=\"iconCls:'icon-objopen',plain:true\" onclick=\"installWare('#com_icon','comType')\">安装</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd id=\"com_install\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t存储节点\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"kvm-set-os\" id =\"stg_icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"kvm-ok\"");
      if (_jspx_meth_c_005fif_005f11(_jspx_page_context))
        return;
      out.write("></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" ");
      if (_jspx_meth_c_005fif_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-options=\"iconCls:'icon-objopen',plain:true\" onclick=\"installWare('#stg_icon','stgType')\">安装</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<dd id=\"stg_install\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"kvm-footer\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"goStep(2)\">&lt;上一步\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"#\" class=\"easyui-linkbutton\" onclick=\"goStep(4)\">下一步\r\n");
      out.write("\t\t\t\t\t\t\t&gt;</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"body kvm-pzjc\" id=\"step4\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">云平台信息：</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" class=\"kvm-create\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"kvm-btn-box active\" id=\"init_icon\" onclick=\"initEnviron('#init-icon')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-wlpz\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon \"></i>一键启动\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"select\" id=\"init-icon\">");
      if (_jspx_meth_c_005fif_005f13(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f14(_jspx_page_context))
        return;
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"kvm-icon-arrow\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"kvm-btn-box\" id=\"\" onclick=\"initEnviron('#check-icon')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"kvm-btn icon-btn-fwqpz\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"kvm-btn-icon \"></i>一键检测\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"select\" id=\"check-icon\">开始</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"kvm-footer\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"goStep(3)\">&lt;上一步\r\n");
      out.write("\t\t\t\t\t\t</a> <a href=\"#\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"iconCls:'icon-ok'\">完成</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'center',border:false\">\r\n");
      out.write("\t\t<div class=\"easyui-panel  kvm-t-wrap\" style=\"width:100%;\"\r\n");
      out.write("\t\t\tdata-options=\"fit:true\">\r\n");
      out.write("\t\t\t<table id=\"operate_log\"class=\"easyui-datagrid\" title=\"操作信息\"\r\n");
      out.write("\t\t\t\tstyle=\"width:100%; height:100%\"\r\n");
      out.write("\t\t\t\tdata-options=\"fitColumns:true,nowrap:false,rownumbers:true\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'time',width:200,align:'center'\">时间</th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'ip',width:200,align:'center'\">主机</th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'event',width:200,align:'center'\">事件</th>\r\n");
      out.write("\t\t\t\t\t\t<th data-options=\"field:'result',width:200,align:'center'\">结果</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t    <div id=\"add_host_dialog\" class=\"easyui-dialog\" title=\"选择物理主机到【环境】\" data-options=\"closed:true,modal:true,collapsible:false,minimizable:false,maximizable:false,fitColumns:true,width:480,height:320,buttons: [{\r\n");
      out.write("            text: '确定',\r\n");
      out.write("            iconCls: 'icon-ok',\r\n");
      out.write("            handler: addHostToEnvrion\r\n");
      out.write("        }, {\r\n");
      out.write("            text: '取消',\r\n");
      out.write("            iconCls: 'icon-cancel',\r\n");
      out.write("            handler: function() {\r\n");
      out.write("                $('#add_host_dialog').dialog('close');\r\n");
      out.write("            }\r\n");
      out.write("        }]\">\r\n");
      out.write("        <table id=\"add_host_dg\" class=\"easyui-datagrid\" style=\"margin-top:5px;width: 100%;\" data-options=\"fitColumns:true,height:240\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th data-options=\"field:'ck',width:100,checkbox:true\"></th>\r\n");
      out.write("                    <th data-options=\"field:'hostid',width:80,align:'center'\">编码</th>\r\n");
      out.write("                    <th data-options=\"field:'hostname',width:100,align:'center'\">主机</th>\r\n");
      out.write("                    <th data-options=\"field:'ipaddr',width:100,align:'center'\">IP地址</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"hidden\" id=\"env_status\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"environId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.environid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"environName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.environname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" id=\"nodeType\">\r\n");
      out.write(" <!-- 存放主机ip,-->\r\n");
      out.write("<input type=\"hidden\" id=\"con_nodes\">\r\n");
      out.write("<input type=\"hidden\" id=\"com_nodes\">\r\n");
      out.write("<input type=\"hidden\" id=\"stg_nodes\">\r\n");
      out.write("<!-- 弹层 -->\r\n");
      out.write("<div id=\"kvmWindow\" class=\"kvm-window easyui-dialog\"\r\n");
      out.write("\tdata-options=\" \r\n");
      out.write("        title: '添加计算节点',\r\n");
      out.write("        modal: true,\r\n");
      out.write("        width: 780,\r\n");
      out.write("        height: 500,\r\n");
      out.write("        closed: true,\r\n");
      out.write("        buttons: [{\r\n");
      out.write("            text: '保存',\r\n");
      out.write("            iconCls: 'icon-ok',\r\n");
      out.write("            handler: addNodeHost\r\n");
      out.write("        }, {\r\n");
      out.write("            text: '取消',\r\n");
      out.write("            iconCls: 'icon-cancel',\r\n");
      out.write("            handler: function() {\r\n");
      out.write("                $('#kvmWindow').dialog('close');\r\n");
      out.write("            }\r\n");
      out.write("        }]\">\r\n");
      out.write("\t<div class=\"kvm-window-left\">\r\n");
      out.write("\t\t<div class=\"title\">研发OS平台主机\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',height:24\" onclick=\"showAddHostDg()\">添加</a>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-delete',height:24\" onclick=\"addHostToEnvrion(0)\">移除</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table id=\"kvmAddTable\">\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"kvm-window-center\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"leftToRight()\">&nbsp;增加&nbsp;&gt;&nbsp;</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" onclick=\"rightToLeft()\">&nbsp;&lt;&nbsp;移除&nbsp;</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"kvm-window-right\">\r\n");
      out.write("\t\t<div class=\"title\">控制节点列表</div>\r\n");
      out.write("\t\t<table id=\"kvmAddShowTable\">\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//上一步、下一步\r\n");
      out.write("function goStep(step) {\r\n");
      out.write("\tif(step===2){\r\n");
      out.write("\t\tvar controlnum=Number($('#controlnum').text());\r\n");
      out.write("\t\tvar computenum=Number($('#computenum').text());\r\n");
      out.write("\t\tvar storagenum=Number($('#storagenum').text());\r\n");
      out.write("\t\tif(controlnum<1||computenum<1||storagenum<1){\r\n");
      out.write("\t\t\t$.messager.alert(\"提示\", \"不满足部署需求，请重新分配节点。\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else if(step===3){\r\n");
      out.write("\t\tif(Number($('#env_status').val())<2){\r\n");
      out.write("\t\t\t$.messager.alert(\"提示\", \"请先完成检查。\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    $(\"#con_install p\").remove();\r\n");
      out.write("        $(\"#com_install p\").remove();\r\n");
      out.write("        $(\"#stg_install p\").remove();\r\n");
      out.write("\t\tvar data = queryByStatus(2); //查询环境检查完成的机器\r\n");
      out.write("        var con_nodes = \"\";\r\n");
      out.write("        var com_nodes = \"\";\r\n");
      out.write("        var stg_nodes = \"\";\r\n");
      out.write("        for (var i in data) {\r\n");
      out.write("            var p = \"<p id=\\\"\" + data[i].ipaddr + \"\\\">\"+\"名称：\" +data[i].hostname+\" IP : \"+ data[i].ipaddr + \"</p>\";\r\n");
      out.write("            if (data[i].contype === '1') {\r\n");
      out.write("                $(\"#con_install\").append(p);\r\n");
      out.write("                con_nodes += data[i].ipaddr + \",\";\r\n");
      out.write("            } \r\n");
      out.write("            if(data[i].comtype === '1') {\r\n");
      out.write("                $(\"#com_install\").append(p);\r\n");
      out.write("                com_nodes += data[i].ipaddr + \",\";\r\n");
      out.write("            } \r\n");
      out.write("            if (data[i].stgtype === '1') {\r\n");
      out.write("                $(\"#stg_install\").append(p);\r\n");
      out.write("                stg_nodes += data[i].ipaddr + \",\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        $(\"#con_nodes\").val(con_nodes);\r\n");
      out.write("        $(\"#com_nodes\").val(com_nodes);\r\n");
      out.write("        $(\"#stg_nodes\").val(stg_nodes);\r\n");
      out.write("\t}else if(step===4){\r\n");
      out.write("\t\tif(Number($('#env_status').val())<5){\r\n");
      out.write("\t\t\t$.messager.alert(\"提示\", \"请先完成安装。\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t \t\r\n");
      out.write("\t$('#step' + step).show().siblings().hide();\r\n");
      out.write("\tindex = step - 1;\r\n");
      out.write("\t$('#stepTab li').eq(index).addClass('active').siblings().removeClass(\r\n");
      out.write("\t\t\t'active');\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function showAddNode(nodeType) {\r\n");
      out.write("\tvar title =\"标题\";\r\n");
      out.write("\tif(nodeType==='conType'){\r\n");
      out.write("\t\ttitle =\"控制节点\";\r\n");
      out.write("\t}else if(nodeType==='comType'){\r\n");
      out.write("\t\ttitle =\"计算节点\";\r\n");
      out.write("\t}else if(nodeType==='stgType'){\r\n");
      out.write("\t\ttitle =\"存储节点\";\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#nodeType').val(nodeType);\r\n");
      out.write("\t$('#kvmWindow').dialog({\r\n");
      out.write("\t\tmodal : true,\r\n");
      out.write("\t\tclosed : false,\r\n");
      out.write("\t\ttitle :title\r\n");
      out.write("\t});\r\n");
      out.write("\t//选中增加\r\n");
      out.write("\t$('#kvmAddTable').datagrid({\r\n");
      out.write("\t\twidth : 320,\r\n");
      out.write("\t\theight : 380,\r\n");
      out.write("\t\tfitColumns : true,\r\n");
      out.write("\t\tnowrap : false,\r\n");
      out.write("\t\tscrollbarSize : 0,\r\n");
      out.write("\t\turl : 'datagrid_data3.json',\r\n");
      out.write("\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\tfield : 'ck',\r\n");
      out.write("\t\t\tcheckbox : true\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 'hostid',\r\n");
      out.write("\t\t\ttitle : '编码',\r\n");
      out.write("\t\t\twidth : 80\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 'hostname',\r\n");
      out.write("\t\t\ttitle : '名称',\r\n");
      out.write("\t\t\twidth : 100\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 'ipaddr',\r\n");
      out.write("\t\t\ttitle : 'IP',\r\n");
      out.write("\t\t\twidth : 100\r\n");
      out.write("\r\n");
      out.write("\t\t} ] ],\r\n");
      out.write("\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryNodeType.do',\r\n");
      out.write("    \tqueryParams: {\r\n");
      out.write("        \tnodeType: nodeType,\r\n");
      out.write("        \tenvironId:$(\"#environId\").val(),\r\n");
      out.write("        \tisNode:0\r\n");
      out.write("    \t},\r\n");
      out.write("\t});\r\n");
      out.write("\t//可选展示\r\n");
      out.write("\t$('#kvmAddShowTable').datagrid({\r\n");
      out.write("\t\twidth : 320,\r\n");
      out.write("\t\theight : 380,\r\n");
      out.write("\t\tfitColumns : true,\r\n");
      out.write("\t\tnowrap : false,\r\n");
      out.write("\t\tscrollbarSize : 0,\r\n");
      out.write("\t\turl : 'datagrid_data3.json',\r\n");
      out.write("\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\tfield : 'ck',\r\n");
      out.write("\t\t\tcheckbox : true\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 'hostid',\r\n");
      out.write("\t\t\ttitle : '编码',\r\n");
      out.write("\t\t\twidth : 80\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 'hostname',\r\n");
      out.write("\t\t\ttitle : '名称',\r\n");
      out.write("\t\t\twidth : 100\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfield : 'ipaddr',\r\n");
      out.write("\t\t\ttitle : 'IP',\r\n");
      out.write("\t\t\twidth : 100\r\n");
      out.write("\r\n");
      out.write("\t\t} ] ],\r\n");
      out.write("\t\turl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/queryNodeType.do',\r\n");
      out.write("    \tqueryParams: {\r\n");
      out.write("        \tnodeType: nodeType,\r\n");
      out.write("        \tenvironId:$(\"#environId\").val(),\r\n");
      out.write("        \tisNode:1\r\n");
      out.write("    \t},\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t//添加主机到环境（云平台）,从环境移除主机\r\n");
      out.write("\tfunction addHostToEnvrion(isAdd){//typeof:number\r\n");
      out.write("\t\tvar rows=null;\r\n");
      out.write("\t\tif(0===isAdd){//remove hosts from kvmAddTable\r\n");
      out.write("\t\t\trows =\t$('#kvmAddTable').datagrid('getChecked');\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tisAdd=1;\r\n");
      out.write("\t\t\trows = $('#add_host_dg').datagrid('getChecked');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    if (rows.length < 1) { \r\n");
      out.write("\t        return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    var hostIds = \"\";\r\n");
      out.write("\t    for (var index = 0; index < rows.length; index++) {\r\n");
      out.write("\t    \thostIds = hostIds + rows[index].hostid + \",\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        type: \"POST\",\r\n");
      out.write("\t        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/addHostToEnviron.do',\r\n");
      out.write("\t        data: {\r\n");
      out.write("\t        \thostIds: hostIds,\r\n");
      out.write("\t            environId: $(\"#environId\").val(),\r\n");
      out.write("\t            environName : $('#environName').val(),\r\n");
      out.write("\t            isAdd :isAdd\r\n");
      out.write("\t        },\r\n");
      out.write("\t        dataType: \"json\",\r\n");
      out.write("\t        success: function(data) {\r\n");
      out.write("\t        \t $('#add_host_dialog').dialog('close');\r\n");
      out.write("\t             $('#kvmAddTable').datagrid('reload');\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction leftToRight(){\r\n");
      out.write("\t\tvar rows = $('#kvmAddTable').datagrid('getChecked');\r\n");
      out.write("\t\tif (rows.length < 1) {\r\n");
      out.write("\t        return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\tfor(var i in rows){\r\n");
      out.write("\t\t\tvar index = $('#kvmAddTable').datagrid('getRowIndex',rows[i]); \r\n");
      out.write("\t\t\t$('#kvmAddTable').datagrid('deleteRow',index);\r\n");
      out.write("\t\t\t$('#kvmAddShowTable').datagrid('appendRow',rows[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction rightToLeft(){\r\n");
      out.write("\t\tvar rows = $('#kvmAddShowTable').datagrid('getChecked');\r\n");
      out.write("\t\tif (rows.length < 1) {\r\n");
      out.write("\t        return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t\tfor(var i in rows){\r\n");
      out.write("\t\t\tvar index = $('#kvmAddShowTable').datagrid('getRowIndex',rows[i]); \r\n");
      out.write("\t\t\t$('#kvmAddShowTable').datagrid('deleteRow',index);\r\n");
      out.write("\t\t\t$('#kvmAddTable').datagrid('appendRow',rows[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//添加节点\r\n");
      out.write("\tfunction addNodeHost() {\r\n");
      out.write("\t    var rows = $('#kvmAddShowTable').datagrid('getRows');\r\n");
      out.write("\t    var hostIds = \"\";\r\n");
      out.write("\t    for (var index = 0; index < rows.length; index++) {\r\n");
      out.write("\t    \thostIds = hostIds + rows[index].hostid + \",\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t    var nodeType = $('#nodeType').val();\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        type: \"POST\",\r\n");
      out.write("\t        url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/addNode.do',\r\n");
      out.write("\t        data: {\r\n");
      out.write("\t        \thostIds: hostIds,\r\n");
      out.write("\t            nodeType: nodeType,\r\n");
      out.write("\t            environId: $(\"#environId\").val() \r\n");
      out.write("\t        },\r\n");
      out.write("\t        dataType: \"json\",\r\n");
      out.write("\t        success: function(data) {\r\n");
      out.write("\t        \tif(data.success){\r\n");
      out.write("\t        \t\t$.messager.alert(\"消息\",data.msg,'info');\r\n");
      out.write("\t        \t}else{\r\n");
      out.write("\t        \t\t$.messager.alert(\"消息\",data.msg,'error');\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t            $('#kvmWindow').dialog('close');\r\n");
      out.write("            \tqueryEnviron();\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t//网络配置检查\r\n");
      out.write("\tfunction checkNet(obj) {\r\n");
      out.write("\t\tif($('#env_status').val()!='0'){//\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(obj).html('<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/osdeploy/image/kwm-loading.gif\" alt=\"\">');\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        type: \"POST\",\r\n");
      out.write("\t        dataType: \"json\",\r\n");
      out.write("\t        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/checkNet.do\",\r\n");
      out.write("\t        async: true,\r\n");
      out.write("\t        data: {\r\n");
      out.write("\t            environId: $(\"#environId\").val(),\r\n");
      out.write("\t            status: 0\r\n");
      out.write("\t        },\r\n");
      out.write("\t        success: function(data) {\r\n");
      out.write("\t        \tif(data.success){\r\n");
      out.write("\t\t        \t$(obj).html('检查通过！ <span class=\"kvm-ok\"></span>');\r\n");
      out.write("\t\t\t\t\t$('#kvmSfqpz').addClass('active');\r\n");
      out.write("\t\t\t\t\t$('#env_status').val('1');\r\n");
      out.write("\t        \t}else{\r\n");
      out.write("\t        \t\t$(obj).html('检查失败！ <span class=\"kvm-error\"></span>');\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t//服务器配置检查\r\n");
      out.write("\tfunction checkServer(obj) {\r\n");
      out.write("\t\tif($('#env_status').val()!='1'){//\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(obj).html('<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/osdeploy/image/kwm-loading.gif\" alt=\"\">');\r\n");
      out.write("\t    $.ajax({\r\n");
      out.write("\t        type: \"POST\",\r\n");
      out.write("\t        dataType: \"json\",\r\n");
      out.write("\t        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/checkServer.do\",\r\n");
      out.write("\t        async: true,\r\n");
      out.write("\t        data: {\r\n");
      out.write("\t            environId: $(\"#environId\").val(),\r\n");
      out.write("\t            status: 1\r\n");
      out.write("\t        },\r\n");
      out.write("\t        success: function(data) {\r\n");
      out.write("\t        \tif(data.success){\r\n");
      out.write("\t\t        \t$(obj).html('检查通过！ <span class=\"kvm-ok\"></span>');\r\n");
      out.write("\t\t        \t$('#env_status').val('2');\r\n");
      out.write("\t\t        \t$('#con_icon a').show();\r\n");
      out.write("\t\t        \t//show \r\n");
      out.write("\t        \t}else{\r\n");
      out.write("\t        \t\t$(obj).html('检查失败！ <span class=\"kvm-error\"></span>');\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t//安装软件\r\n");
      out.write("\tfunction installWare(obj,nodeType) {\r\n");
      out.write("\t\t$(obj+' .kvm-error').remove();\r\n");
      out.write("\t\tvar ins_host_ip = \"\";\r\n");
      out.write("\t    if (nodeType === 'conType') {\r\n");
      out.write("\t        ins_host_ip = $(\"#con_nodes\").val();\r\n");
      out.write("\t    } else if (nodeType === 'comType') {\r\n");
      out.write("\t        ins_host_ip = $(\"#com_nodes\").val();\r\n");
      out.write("\t    } else if (nodeType === 'stgType') {\r\n");
      out.write("\t        ins_host_ip = $(\"#stg_nodes\").val();\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if (ins_host_ip) {\r\n");
      out.write("\t        ins_host_ip = ins_host_ip.substring(0, ins_host_ip.length - 1);\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t        $.messager.alert(\"info\", \"没有设备进行安装\");\r\n");
      out.write("\t        return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    $(obj+' a').hide();\r\n");
      out.write("\t\t$(obj).append('<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/osdeploy/image/kwm-loading.gif\" alt=\"\">');\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t        type: \"POST\",\r\n");
      out.write("\t        dataType: \"json\",\r\n");
      out.write("\t        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/installWare.do\",\r\n");
      out.write("\t        async: true,\r\n");
      out.write("\t        data: {\r\n");
      out.write("\t            nodeType: nodeType,\r\n");
      out.write("\t            ins_host_ip: ins_host_ip,\r\n");
      out.write("\t            environId :$(\"#environId\").val()\r\n");
      out.write("\t        },\r\n");
      out.write("\t        success: function(data) {\r\n");
      out.write("\t        \t$(obj+' img').remove();\r\n");
      out.write("\t        \tif(data.success){\r\n");
      out.write("\t        \t\t$(obj).prepend('<span class=\"kvm-ok\"></span>');\r\n");
      out.write("\t        \t\t$(obj).parents('dl').next().find('.kvm-set-os').children('a').show();\r\n");
      out.write("\t        \t\tif (nodeType === 'stgType') {\r\n");
      out.write("\t\t        \t\t $('#env_status').val('5');\r\n");
      out.write("\t\t     \t    }\r\n");
      out.write("\t        \t}else{\r\n");
      out.write("\t        \t\t$(obj).prepend('<span class=\"kvm-error\"></span>');\r\n");
      out.write("\t        \t\t$(obj+' a').show();\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("//一键部署\r\n");
      out.write("\r\n");
      out.write("function initEnviron(obj) {\r\n");
      out.write("\tif(!canbeinit){\r\n");
      out.write("\t\treturn ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($('#env_status').val()!='5'){//\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tcanbeinit = false;\r\n");
      out.write("\t$(obj).html('<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/web/osdeploy/image/kwm-loading.gif\" alt=\"\">');\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/osdeploy/initEnviron.do\",\r\n");
      out.write("        async: true,\r\n");
      out.write("        data: {\r\n");
      out.write("            environId: $(\"#environId\").val()\r\n");
      out.write("        },\r\n");
      out.write("        success: function(data) {\r\n");
      out.write("         \tif(data.success){\r\n");
      out.write("        \t\t$(obj).html('启动成功！ <span class=\"kvm-ok\"></span>');\r\n");
      out.write("        \t\t$('#env_status').val('6');\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\t$(obj).html('启动失败！ <span class=\"kvm-error\"></span>');\r\n");
      out.write("    \t\t\tcanbeinit =true;\r\n");
      out.write("    \t\t}\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /icp/include/taglib.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /icp/include/taglib.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /web/osdeploy/environMg.jsp(253,51) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status eq 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("onclick=\"checkNet('#net-icon')\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /web/osdeploy/environMg.jsp(257,44) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('开');
        out.write('始');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /web/osdeploy/environMg.jsp(257,99) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status gt 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("检测通过<span class=\"kvm-ok\"></span>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /web/osdeploy/environMg.jsp(260,25) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status gt 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("class=\"kvm-btn-box active\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /web/osdeploy/environMg.jsp(261,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("class=\"kvm-btn-box\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent(null);
    // /web/osdeploy/environMg.jsp(265,47) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 2}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('开');
        out.write('始');
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f6.setParent(null);
    // /web/osdeploy/environMg.jsp(265,102) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status gt 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
    if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("检测通过<span class=\"kvm-ok\"></span>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f7.setParent(null);
    // /web/osdeploy/environMg.jsp(281,31) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 3}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
    if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("style=\"display: none\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f8.setParent(null);
    // /web/osdeploy/environMg.jsp(282,48) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status ne '2'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
    if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("style=\"display: none\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f9.setParent(null);
    // /web/osdeploy/environMg.jsp(293,31) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 4}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
    if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("style=\"display: none\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f10.setParent(null);
    // /web/osdeploy/environMg.jsp(294,48) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status ne '3'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
    if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("style=\"display: none\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f11 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f11.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f11.setParent(null);
    // /web/osdeploy/environMg.jsp(305,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f11.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 5}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f11 = _jspx_th_c_005fif_005f11.doStartTag();
    if (_jspx_eval_c_005fif_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("style=\"display: none\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f11.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f11);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f12 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f12.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f12.setParent(null);
    // /web/osdeploy/environMg.jsp(306,48) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f12.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status ne '4'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f12 = _jspx_th_c_005fif_005f12.doStartTag();
    if (_jspx_eval_c_005fif_005f12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("style=\"display: none\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f12.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f12);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f13 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f13.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f13.setParent(null);
    // /web/osdeploy/environMg.jsp(329,46) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f13.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status lt 6}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f13 = _jspx_th_c_005fif_005f13.doStartTag();
    if (_jspx_eval_c_005fif_005f13 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('开');
        out.write('始');
        int evalDoAfterBody = _jspx_th_c_005fif_005f13.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f13);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f14 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f14.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f14.setParent(null);
    // /web/osdeploy/environMg.jsp(329,101) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f14.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OsDeployEnvironVo.status gt 5}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f14 = _jspx_th_c_005fif_005f14.doStartTag();
    if (_jspx_eval_c_005fif_005f14 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("启动成功<span class=\"kvm-ok\"></span>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f14.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f14);
    return false;
  }
}
